### ISSUE TITLE
how to forcefully create new instance with dice version 2?

### ISSUE THREAD

**Issue by hartono-sulaiman-kaskus** [Level-2/Dice#100]
Hi Tom,

What if i want to forcefully create new instance with dice version 2?

I can do this in version 1.4.x by passing parameter forceNewInstance = true in create method
https://github.com/Level-2/Dice/blob/v1.4/Dice.php#L25

**Comment by TomBZombie** [comment]
You can now do this using a named instance which gives you significantly more control over the new instance:

```php

$dice->addRule('$NamedInstance', ['
    'instanceOf' => 'ClassName',
   'constructParams' => [ 'parameters', 'for', 'new', 'instance'
]);

$dice->addRule('ClassThatNeedsNewInstance', [
    'substitutions' => '$NamedInstance'
]);

$dice->create('ClassThatNeedsNewInstance');
```

This will pass a new instance that uses a specific configuration that is supplied by adding rules to the named instance. Using `forceNewInstance` there was no way to pass constructor arguments to the new instance.
