### ISSUE TITLE
instanceOf and closures

### ISSUE THREAD

**Issue by aaronpeterson** [Level-2/Dice#102]
I like to key my dependency injection by interface FQCN.  Sometimes I need to process some logic about configuration, system configuration, etc before I return an instance; or otherwise customize instantiation at the injector level.

This is covered by #82 but I'd be curious why instanceOf can't be a closure.  I was going to submit a PR but wondered if I was missing something; major performance hit, etc.

Love how simple and sweet Dice is.  Thank you.

**Comment by TomBZombie** [comment]
Firstly, apologies for the delayed response, I've had a very busy few weeks! 

I'm not sure I fully understand what you're asking, do you want to do this:


```php
$dice->addRule('Foo', ['instanceOf' => function() { 
return new Bar;
}
```


This is certainly possible to add, however I'm not sure there's really any advantage over setting this up as a substitution rule? Can you demonstrate a use-case where this would be useful?

**Comment by TomBZombie** [comment]
it's been a year... closing. Feel free to reopen and respond.

**Comment by solleer** [comment]
What if you do
```
['instanceOf' => ['Factory', 'getObj']]
```
So in other words you are able to do the same thing you can do with substitutions

**Comment by TomBZombie** [comment]
A closure there would likely be more flexible as it would allow arguments, variables, etc but I'd like to see a real use-case for this rather than just using the closure as a substitution rule.

**Comment by solleer** [comment]
Here is an example
I have this in my index.php
```php
$diceLoaderJson = new Dice\Loader\Json;
$dice = $diceLoaderJson->load('Config/Dice/Framework.json');
$diceConfig = $dice->create('$config_dice');
$dice = $diceLoaderJson->load($diceConfig->getFiles());
```
I also have this in `Config/Dice/Framework.json`
```json
"*" : {
        "substitutions" : {
            "Dice\\Dice" : {
                "instance" : ["Dice\\Loader\\Json", "load"],
                "params" : [
                    {"instance": ["$config_dice", "getDiceFiles"]}
                ]
            }
        }
    }
```
It would be much easier if I could do this
```json
"Dice\\Dice" : {
    "instanceOf" : {
        "instance" : ["Dice\\Loader\\Json", "load"],
        "params" : [
              {"instance": ["$config_dice", "getDiceFiles"]}
        ]
    }
}
