### ISSUE TITLE
Applying global or ancestor rules when class has rules

### ISSUE THREAD

**Issue by xoogu** [Level-2/Dice#105]
When a class has it's own rules then any registered global or ancestor rules are not applied. (On your example page it notes this behaviour for global rules, but I don't think it mentions it for ancestor rules).

```
namespace Letters;
class Letters {
	
}
class A extends Letters{
	function __construct($a){
		$this->_a = $a;
	}
	function geta(){
		return $this->_a;
	}
}
interface IB {
	function hello();
}
class B extends Letters implements IB{
	function hello(){
		return 'hi';
	}
}
class C extends Letters {
	function __construct(\Letters\A $a, \Letters\IB $b){
		$this->_A = $a;
		$this->_B = $b;
	}
	function greet(){
		return $this->_B->hello().' '.$this->_A->geta();
	}
}
```
```
$a = new \Letters\A('AAA');
$dice = new \Dice\Dice();
$dice->addRule('*', ['substitutions' => ['Letters\\A' => $a]]); //or $dice->addRule('Letters', ['substitutions' => ['Letters\\A' => $a]]);
$dice->addRule('Letters\\C',['shared' => true, 'substitutions' => ['Letters\\IB' => ['instance' => 'Letters\\B']]]);
$dice->addRule('Letters\\B', ['shared' => true]);
$c = $dice->create('Letters\\C');
var_dump($c->greet()); //get 'Hi ' rather than expected 'Hi AAA'
var_dump($a->geta()); //'AAA'
```

While this can be dealt with outside of Dice by getting and merging existing rules when setting a new rule

`$dice->addRule('Letters\\C', array_merge_recursive(['shared' => true, 'substitutions' => ['Letters\\IB' => ['instance' => 'Letters\\B']]], $dice->getRule('*'),$dice->getRule('Letters')));`

It would be nice if Dice could keep looking for rules even after it finds rules set on the class.

**Comment by TomBZombie** [comment]
This is exactly how it works, When a rule is added it is merged with the existing rule that is applied to the selected class.

**Comment by xoogu** [comment]
But the rule is not merged with ancestor or global rules, and when it finds the rule for the class then it does not continue to look for ancestor or global rules.

On my example I would expect `$c->greet()` to output 'Hi AAA' but instead it only outputs 'Hi '. Because the global rule on C is ignored, and so it injects a new instance of A into C rather than using the existing instance of A set in the global rule. Unless I'm doing something wrong in my example that is causing the global rule to be ignored?

**Comment by TomBZombie** [comment]
Ah I see the problem, because you're setting `substitutions` on both instances, one is overriding the other. I've changed array_merge to array_merge_recursive and it will now resolve this issue.

**Comment by xoogu** [comment]
Ah actually I see the problem now - I'm using the PHP5.4 compatible branch, where getRule only gets rules applied to the current class if they exist. Either that or I downloaded the wrong file.
