### ISSUE TITLE
XML config reading of values from classes not working

### ISSUE THREAD

**Issue by Kocik** [Level-2/Dice#106]
dice.xml:

```
<?xml version="1.0"?>
<dice>
    <rule>
        <name>Config</name>
        <shared>true</shared>
    </rule>
    <rule>
        <name>Thing</name>
        <shared>true</shared>
        <constructParams>
            <param>{Config::dbServer}</param>
            <param>{Config::dbUser}</param>
            <param>{Config::dbPassword}</param>
        </constructParams>
    </rule>
</dice>
```

PHP:

```

class Config {
    public $dbServer = 'A';
    public $dbPassword = 'B';
    public $dbUser = 'C';
}
class Thing {
    function __construct($a, $b, $c) {
        var_dump( $a, $b, $c );
    }
}
$dice = new \Dice\Dice;
$diceLoader = new \Dice\Loader\Xml;
$diceLoader->load( __DIR__ . '/../config/dice.xml', $dice );


$pdo = $dice->create( Thing::class );

```

output:

```
string '{Config::dbServer}' (length=18)
string '{Config::dbUser}' (length=16)
string '{Config::dbPassword}' (length=20)
```

Also if I use `<construct>` (as documentation suggests) instead of `<constructParams>` it outputs `null` three times.

**Comment by daniel-meister** [comment]
AFAICT, this exact feature has been removed in 103e79e89b3555ceb7e3724d10916be4f6831e5b (going from version 1.1 to version 2. Alternatively, you could e.g. use the ```<instance>``` tag.

```
    <rule>
        <name>Thing</name>
        <shared>true</shared>
        <constructParams>
            <param><instance>Config</instance></param>
        </constructParams>
    </rule>
```

with the following PHP file

```
class Config {
    public $dbServer = 'A';
    public $dbPassword = 'B';
    public $dbUser = 'C';
}
class Thing {
    function __construct($c) {
        var_dump( $c->dbServer, $c->dbPassword, $c->dbUser );
    }
}
```

**Comment by Kocik** [comment]
Documentation has to be out of date then ( https://r.je/dice.html ).

Thanks for the alternative solution. But is there a way to do that when `Thing` is actually `PDO`?

**Comment by daniel-meister** [comment]
Yes, I agree the documentation seems outdated.

First thing that comes to mind is extending the ```PDO``` class, implement a constructor that calls ```parent::__construct($c->dbServer, $c->dbUser, $c->dbPassword)```, and write a substitution rule for PDO.

I'll get back to you if I can come up with a more elegant solution.

**Comment by TomBZombie** [comment]
I've deprecated the XML loader in the new version of Dice in favour of JSON as it maps a lot more easily to a native PHP data structure. As this is now a few years old I'll close the issue.
