### ISSUE TITLE
Expand instances allowing construct params

### ISSUE THREAD

**Issue by solleer** [Level-2/Dice#111]
Currently when creating instances as constructParams or substitutions you use `["instance" => "Class"]`
This also supports calling a function on the object and returning the result of the function call like `["instance" => ["Class", "function"], "params" => []]`
I am suggesting allowing construct params in the instance statement like `["instance" => "Class", "params" => []]`

**Comment by TomBZombie** [comment]
This is currently possible with named instances e.g. `["instance" => "$NamedInstance"]` and defining the constructparams on the instance, but I can see how this shorthand would be useful.

**Comment by TomBZombie** [comment]
I've added this. I've set it so that any arguments in the `params` array have priority over anything in `ShareInstances` from containing rules so there may be some instances where doing this and having `ShareInstances` set doesn't quite work as you might expect, however this is the better way.
