### ISSUE TITLE
Using Dice with existing objects

### ISSUE THREAD

**Issue by JPry** [Level-2/Dice#112]
I'm working with an existing application that unfortunately makes heavy use of global objects. I would like to start using Dice and bringing in pieces of true OOP as much as possible. My question is this: Is it possible to have Dice capture a pre-existing object for injecting?

I've done some experimentation, and it appears that Dice will always use Reflection to create an initial object. I attempted to create a closure attached to the `instance` parameter for a rule, but that didn't seem to work:

```php
$dice = new \Dice\Dice();
$rule = [
    'shared' => true,
    'inherit' => true,
    'instance' => function() {
        global $my_object;
        return $my_object;
    }
];

$dice->addRule('my_object', $rule);
```

The object is indeed shared as expected, but it is creating a new instance rather than using the global instance.

I understand that this isn't exactly how Dice is intended to work. However, I think it may be useful to allow injection of existing object into Dice. Maybe something like the following?

```php
global $some_object;
$dice = new \Dice\Dice();
$dice->addInstance('some_object', $some_object);
```

**Comment by solleer** [comment]
You can set a closure substitution

**Comment by JPry** [comment]
@solleer 

> You can set a closure substitution

Like this?

```php
$dice = new \Dice\Dice();
$rule = [
    'substitutions' => [
        'wpdb' => [
            'instance' => function() {
                global $object;
                return $object;
            }
        ]
    ]
];
$dice->addRule('*', $rule);
```

That may work once Dice creates an object on its own, but it still seems to be ignoring the object that is created outside of Dice. I made a very simple test file, and I'm seeing that the global object is different than the Dice-created object, although Dice *is* properly reusing the same object according to my rule:

```php
require_once(__DIR__ . '/vendor/autoload.php');

class myObjet {

    public $rand = 0;

    public function __construct()
    {
        $this->rand = rand();
    }

    public function __toString() {
        return print_r($this, true);
    }
}

global $object;
$object = new myObjet();

$dice = new \Dice\Dice();
$general_rule = [
    'substitutions' => [
        'myObjet' => [
            'instance' => function() {
                global $object;
                return $object;
            }
        ]
    ]
];
$dice->addRule('*', $general_rule);
$object_rule = [
    'shared' => true,
    'inherit' => true,
];

$dice->addRule('myObjet', $object_rule);

print_r($object); // Gives one instance of the object
print_r($dice->create('myObjet')); // Gives a second instance of the object
print_r($dice->create('myObjet')); // Gives the second instance of the object again
```

If I'm completely misunderstanding how this is supposed to work, I would appreciate a code example that can help set me straight 😄

**Comment by JPry** [comment]
Here's some sample output from the script in my previous comment:

```
myObjet Object
(
    [rand] => 978206411
)
myObjet Object
(
    [rand] => 1336553230
)
myObjet Object
(
    [rand] => 1336553230
)
```

Note that the 1st object is different than the 2nd and 3rd objects.

**Comment by TomBZombie** [comment]
This is the expected behaviour because `'substitutions` is only applied to constructor arguments. This will work:

```php
require_once(__DIR__ . '/vendor/autoload.php');

class myObjet {

    public $rand = 0;

    public function __construct()
    {
        $this->rand = rand();
    }

    public function __toString() {
        return print_r($this, true);
    }
}

class myOtherObject {

 public $myObject;
 public function __construct(myObject $myObject) {
    $this->myObject = $myObject;
 }
}

global $object;
$object = new myObjet();

$dice = new \Dice\Dice();
$general_rule = [
    'substitutions' => [
        'myObjet' => [
            'instance' => function() {
                global $object;
                return $object;
            }
        ]
    ]
];
$dice->addRule('*', $general_rule);
$object_rule = [
    'shared' => true,
    'inherit' => true,
];

$dice->addRule('myObjet', $object_rule);

print_r($object); // Gives one instance of the object
print_r($dice->create('myOtherObject')->myObject); 
print_r($dice->create('myOtherObject')->myObject); 
```

**Comment by JPry** [comment]
Thanks for the clarification @TomBZombie. I was probably over-thinking this one. In short, for injection into other classes, use Dice with a substitution rule. For accessing the existing object elsewhere, don't bother trying to do it with Dice.
