### ISSUE TITLE
Class MongoDB\Driver\Manager is an internal class marked as final that cannot be instantiated without invoking its constructor

### ISSUE THREAD

**Issue by MichaelBrenden** [Level-2/Dice#117]
error caused by this

$MongoClient = $dice->create( 'MongoDB\Driver\Manager',
[
                    'mongodb://localhost:27017/'
                        , [
                            'replicaSet' => 'rs1'
                            , 'w' => 0
                            , 'wTimeoutMS' => 900000000 // write 15 min, in millisecs
                            , 'readPreference' => \MongoClient::RP_NEAREST
                        ]
                    ]
 );

**Comment by TomBZombie** [comment]
I can't replicate this on PHP 7, however I don't have a mongo installation available, but this looks like the class constructor is being called correctly:

```php
<?php
phpinfo();
require_once 'Dice.php';

$dice = new Dice\Dice();
$MongoClient = $dice->create( 'MongoDB\Driver\Manager', ['127.0.0.1', [], []]);

``` 

I'll grab a 5.6 vagrant box and test it out but I think this is fixed in PHP7.

**Comment by TomBZombie** [comment]
Unfortunately it's difficult to find a PHP5.6 installation. I found the ArchLinux package but it doesn't include the mongodb extension. I'll see if I can get it installed, however, the best fix for this is to upgrade to a more recent PHP version.

**Comment by k00ni** [comment]
@TomBZombie: You could use a Docker container, which provides a ready-to-use PHP environment to test it. [Link to DockerHub](https://hub.docker.com/_/php/).

**Comment by TomBZombie** [comment]
I've found a Vagrant box with PHP56 and mongo. I'm not a fan of docker, I still have to run it in a VM to avoid the inherent security issues so it ends up being as resource heavy as a vagrant box

**Comment by TomBZombie** [comment]
This must have been fixed in PHP5.6 or earlier. I'm unable to replicate this issue even on 5.6. 

@MichaelBrenden if you are still having this issue, which PHP version are you using?

**Comment by AriartWt** [comment]
I'me having a similar error in PHP 7.2 with the 3.0 Dice version. 
It seems to be caused by the call $class->newInstanceWithoutConstructor() when a class extends a php internal class AND is declared as final. 
A quick test : 

    <?php
    interface ICacheSystem{}
    final class APCUCacheSystem extends \APCUIterator implements ICacheSystem{
         public function __construct(){
              parent::__construct(null,APC_ITER_ALL);
         }
    }

    $this->_dice = new Dice();
    $dice->addRules([
        ICacheSystem::class => [
            'instanceOf' => APCUBasedCache::class,
            'shared' =>true
        ]
    ]);
    $dice->create(ICacheSystem::class); //Throw : 
    //Fatal error: Uncaught ReflectionException:
    // Class APCUBasedCache is an internal class marked as final 
    // that cannot be instantiated without invoking its constructor in ....


Note that removing the 'final' when define APCUBasedCache solve the problem. I've to keep it for some conceptual reasons so I try to find an other solution.

**Comment by TomBZombie** [comment]
That's interesting, this class works:

```php
final class FinalInternal extends \stdClass {

}
```

It's final and internal so should trigger the issue. I wonder what's different about `final class APCUCacheSystem extends \APCUIterator `?  Are there any other classes that cause this?

**Comment by TomBZombie** [comment]
I realise this is a 2 year old issue, and mostly mitigated  by using PHP > 5.6, but I've amended the code to avoid this issue in the few  cases it may still be applicable.
