### ISSUE TITLE
Any way to have Dice "adopt" already- / alternately-created objects?  Not create() but adopt() ?

### ISSUE THREAD

**Issue by MichaelBrenden** [Level-2/Dice#118]
This would (apparently) completely side-step the amazing nonsense that's been going on for almost one year (and probably has a good three years to-go) in regards to the new (AKA, throw everything before away, start completely over, and screw 100% of the early adopters) MongoDB + PHPLIB driver + userland for PHP.

**Comment by MichaelBrenden** [comment]
Can this be done?

namespace my_ns;
$MC = new \MongoDB\Client( 'mongodb://localhost:27017'
			, [
				'replicaSet' => 'rs1'
				, new \MongoDB\Driver\WriteConcern( "0" )
				, 'wTimeoutMS' => 900000000 // write 15 min, in millisecs
				, new \MongoDB\Driver\ReadPreference( \MongoClient::RP_NEAREST )
			]
			, [] // [] necessary because MongoDB\Client needs an array; leaving this blank makes/lets Dice pass a string or whatever, which bombs MongoDB\Client
 );

$dice = new \Dice\Dice;
$dice->addRule( 'my_ns\MongoClient', [ 'shared' => true ] );
$MongoClient = $dice->adopt( my_ns\MC );

**Comment by TomBZombie** [comment]
Is there any reason you can't use this?

```php
$dice->addRule('MongoDb\Client', ['shared' => true,
'constructParams' => 'mongodb://localhost:27017'
, [
'replicaSet' => 'rs1'
, new \MongoDB\Driver\WriteConcern( "0" )
, 'wTimeoutMS' => 900000000 // write 15 min, in millisecs
, new \MongoDB\Driver\ReadPreference( \MongoClient::RP_NEAREST )
]
, [] ]);


$client = $dice->create('MongoDb\Client');
```

**Comment by TomBZombie** [comment]
Take a look at https://github.com/Level-2/Dice/issues/112 for an example of how to use an existing object using substitutions.

**Comment by TomBZombie** [comment]
Closing, if the answer in #112 doesn't suffice, please feel free to reopen this.
