### ISSUE TITLE
"share" argument from "create" method

### ISSUE THREAD

**Issue by cdoublev** [Level-2/Dice#121]
Hello Tom,

Thank you for sharing Dice (and your posts on MVC). It's not an issue, but I can't find why the third argument `array $share` exists inside the `create` method. It is not documented [on your site](https://r.je/dice.html)... : 

> ## Class API
> create($component [, array $constructorParameters])

... and I think it is transformed/evaluated anywhere. Am I missing any use of it ?

**Comment by TomBZombie** [comment]
This argument is used internally when `$rule['shareInstances']` is set. Dice creates instances recursively so calls `create` internally and sometimes needs to provide additional instances to an instance when it's created, you shouldn't need to ever use this parameter if you're calling `create` yourself.

**Comment by cdoublev** [comment]
I didn't spot this recursive call, sorry. Thank you for your explanation.
