### ISSUE TITLE
Q: using Dice with Zend Diactoros Request

### ISSUE THREAD

**Issue by alexflorea2** [Level-2/Dice#123]
Hi,

```
Not sure if this Q belongs here, but I thought I'd try. 
I'll delete it if inappropriate. Thx!
```

I'm using Dice for a small project and it's great so far. I am also using the PSR7 Zend Diactoros for requests and nikic fast route.

I got Dice working for Twig, DB and all the rest of my classes using the examples from docs, but I am unable do figure out how to use it to pass a Request $request to my controllers.

I realize this may not be entirely a Di question, but I would appreciate if you could at least point me in the right direction.

controller code:
```
use Psr\Http\Message\{ServerRequestInterface,ResponseInterface};

class BaseController
{
    public function index(ServerRequestInterface $request)
    {
        dump($request);
        return view('homepage/index.html');
    }
}
```

app init code:
```
$dependency_injector = new Dice();

$rule_request = ['substitutions' => [
    'Psr\\Http\\Message\\ServerRequestInterface' => ['instance'=>function(){
    return Zend\Diactoros\ServerRequestFactory::fromGlobals();
}]];


$midEngine = new MiddlewareEngine($dependency_injector);
$midEngine->add(\App\Middleware\Router::class);

$response = new Zend\Diactoros\Response();
$request = Zend\Diactoros\ServerRequestFactory::fromGlobals();

$final = $midEngine($request, $response);

$emitter = new SapiEmitter();
$emitter->emit($final);
exit;
```

in router code:
```
call_user_func_array([$this->app->di->create($handler[0]),$handler[1]],$vars)
```
where $this->app->di is Dice and $handler is 
```
array(2) {
  [0]=>
  string(30) "App\Controllers\BaseController"
  [1]=>
  string(5) "index"
}
```

#1 as my route has no param first error was that I was passing to few params, so i tried doing this in router, which calls the index method of the controller and passes $request
```
$class = new \ReflectionClass($handler[0]);
$method = $class->getMethod($handler[1]);
foreach ($method->getParameters() as $param) {
            dump($param->getClass()->getName());
            dump($this->app->di->getRule($param->getClass()->getName()));
            $vars[] = $this->app->di->create($param->getClass()->getName());
        }
call_user_func_array([$this->app->di->create($handler[0]),$handler[1]],$vars);
```
#2 now I have my param passed but the error is 
```
Uncaught Error: Cannot instantiate interface Psr\Http\Message\ServerRequestInterface
```

I have a feeling I'm using this all wrong, maybe Dice needs to create the ```$midEngine``` as now I create a response and request object myself.

Any advice would be great, I'm trying to wrap my head around how a mini framework should revolve around a Di.

Thanks,
Alex

**Comment by garrettw** [comment]
The first thing I see is that you've created the Dice substitution rule in `$rule_request` but you never added that rule to the Dice object.

So you might as well change it to this:
```php
$dependency_injector = new Dice();

$dependency_injector->addRule('*', ['substitutions' => [
    'Psr\\Http\\Message\\ServerRequestInterface' => ['instance' => function() {
        return Zend\Diactoros\ServerRequestFactory::fromGlobals();
    }]
]]);
```

**Comment by alexflorea2** [comment]
Thanks for pointing that out. Also I was not aware I can use wildcards, so that's awesome!

With your code, If I move the ```ServerRequestInterface $request``` from the ```index``` function of the controller to the ```construct``` it looks like it's working.   
If I leave it as it was (as param to thte index function) it still says``` Uncaught Error: Cannot instantiate interface Psr\Http\Message\ServerRequestInterface```

controller code:
```
use Psr\Http\Message\{ServerRequestInterface,ResponseInterface};

class BaseController
{
    public function __construct(ServerRequestInterface $request)
    {
        dump($request); // Works !
    }

    public function index()
    {
        return view('homepage/index.html');
    }
}
```

But on all the tuts and/or frameworks examples, eg Laravel, Slim, etc you see more of the same, like what I tried, to pass a Request object to the function itself, not the controller, even though you do not need to specify the request as a param when setting up routes.

This is well beyond help with Dice, I am aware of that. And my stuff is working now, but it's bugging the hell out of me cause I don't understand how is that done haha.

***Thanks again!***

**Comment by garrettw** [comment]
Oh ok, I understand better now.
First of all, `'*'` is the only wildcard Dice understands, so don't get too happy. 😉

Normally I would tell you that you should use an `instanceOf` rule for Dice instead of a `substitutions` rule to do what you're wanting -- but since the object you're wanting to substitute is created during instantiation by an anonymous function, Dice's `instanceOf` won't work with that as it can only take a class name.

So I think what you'd have to do is copy a bigger chunk of Dice's code for the `substitutions` rule and adapt it to your needs. You're on the right track with that code block you added to your router at #2 above. Unfortunately, Dice isn't really meant to do what you're trying to do.

Is there any way your middleware can pass the $request object to the Router, and the Router can just pass it to the index() method when it calls it?

**Comment by TomBZombie** [comment]
Actually you should just be able to use 

`[

            'call' => [

                ['index', []]
]`
 to have dice  auto-resolve the arguments for the index function. This might be a useful feature so a more explicit method of doing this might be better.

**Comment by garrettw** [comment]
Tom, I think you meant to use 3 backticks to surround your code block ;)

**Comment by TomBZombie** [comment]
Yes, thanks!

What I posted above should *sort of* work, the problem is currently Dice gives you no way to access the return value of the called function so you wouldn't be able to access the called template.

**Comment by TomBZombie** [comment]
I've updated Dice so you can now get the return value from 'call' functions using a callback e.g.

```

            'call' => [

                ['index', [], function($return) {
                    echo 'index returned: ' . $return;
               }]
]
```

**Comment by alexflorea2** [comment]
Ok, thanks for all the help, I'll give it a try asap
