### ISSUE TITLE
New independent benchmark results!

### ISSUE THREAD

**Issue by garrettw** [Level-2/Dice#124]
Today, user "kocsismate" has released the [latest results](https://rawgit.com/kocsismate/php-di-container-benchmarks/master/var/benchmark.html) of his DIC benchmarking suite, which include Dice.

Looks like Aura handily beats Dice most of the time. I wonder why.
Anyway, I just thought you would find this interesting.

**Comment by TomBZombie** [comment]
interesting, I wonder whether the tests are actually doing the same thing. By default Dice creates a new instance using $dice->create() whereas most containers return the same instance each time.

Unless the code for Aura has changed significantly, it does considerably more processing each time an object is created than Dice ever does.

**Comment by TomBZombie** [comment]
Unfortunately I don't have enough time to faff around with docker to get it working... not sure why we can't just use php run.php!

**Comment by TomBZombie** [comment]
Having looked at the code it doesn't really do what it says... the startup time (time to autoload classes/read config files) is not actually measured.. so... pointless.
