### ISSUE TITLE
'instance' as a key in constructor arguments

### ISSUE THREAD

**Issue by paramdhal** [Level-2/Dice#125]
When passing arguments to the constructor for the create method you can not pass an array which has a key of 'instance' in it. This will try and create a new class with the value from that key. 

```php
$dice = new \Dice\Dice();
class A{
	public function __construct($array){	
	}
}	
$dice->create(A::class,[['instance'=>2]]);
```

**Comment by garrettw** [comment]
I'm working on something with a new API that would fix this limitation.

**Comment by TomBZombie** [comment]
Unfortunately without breaking backwards compatibility with a considerable number of existing projects, this isn't easy to fix.

However, as a workaround this will work:


$dice = new \Dice\Dice();
class A{
	public function __construct($array){	
	}
}	
$dice->create(A::class,[['instance'=>
function() {
return ['instance' => 2];
}
]]);
```

I'll try to think of some better methods of fixing this, but for now the above workaround will work.

**Comment by paramdhal** [comment]
Thanks @TomBZombie and @garrettw . Ill use a workaround for now :)

**Comment by MrBenGriffin** [comment]
Instead of using a word like 'instance', could you not replace it with a unique class constant, something like 
`const instance = Dice::class . 'instance';`

alternatively, for backwards compatibility, a check using class_exists within expand() would work, no?
 `else if(class_exists($param['instance'])) return $this->create($param['instance'], array_merge($args, $share));`

**Comment by TomBZombie** [comment]
The reason for `'instance'` is that it's JSON compatible, obviously we can't use a constant in JSON. But yes, you're right. Perhaps it should be `'--dice-instance'` or similar.  For clarity though, we could use `Dice::INSTANCE' in PHP and `'Dice::INSTANCE` in JSON. 

The biggest issue here is backwards compatibility.

**Comment by solleer** [comment]
What about the class exists test

**Comment by MrBenGriffin** [comment]
@solleer, Yeah.. Imagine you have a user-generated array that has something like..

`['instance'=>'stdClass']`
So in this case, there would be a false positive. We've got all sorts of things being passed round in all sorts of arrays which are generating instances in 'factory' classes which are nothing much more than Dice::create();

In the docs somewhere, Tom suggests that Dice can eliminate many factories, but for the stuff that we've been doing, we've got quite a few of them. They all look like following, (and therefore the contents of what are being passed over to Dice::create() belongs to the non-dice configuration space.

```
class Factory extends AbstractFactory{
	public function create(...$i) : myInterface {
		$class = array_shift($i);
		return $this->services->get($class, $i);
}

```

**Comment by TomBZombie** [comment]
Yes, this creates a sort of god of the gaps style bugfix. I can imagine situations where a class name does exist. 'User' immediately springs to mind.

@MrBenGriffin I had an email exchange with someone with a similar setup (forgive me it might even have been you) and we came up with a couple of potential solutions. I'll see if I can find it.

**Comment by MrBenGriffin** [comment]
On the train right now, but our use cases involve many live dynamic arrays driven by xml and database tables, so we cannot know the number of instances required by a process 😂

I think it was me... 😄

**Comment by solleer** [comment]
To avoid a BC break you could require an option to be set to change it to the new way

**Comment by MrBenGriffin** [comment]
Well, we also live in a branch managed world, so it could be possible to maintain a legacy branch without too much work, bearing in mind the strengths of git for version management. Adding version configuration/initialisation is really nice, but it increases the complexity of code as one has to refactor into version subclasses (or use a similar strategy). However at least one could implement a Dice rule to choose which version of Dice is to be used.  Still, it's a lot of work.

**Comment by TomBZombie** [comment]
I'm working on a 3.0 branch with BC breaks including this one. Since it's easy enough to have composer use a particular version it's not going to be a particular problem.

For anyone with json config the fix willl be as simple as a find and replace.
