### ISSUE TITLE
constructor with substitution doesnt get shared instances

### ISSUE THREAD

**Issue by Steffen1996** [Level-2/Dice#126]
Wrote an interface, said dice to substitute it with my implementation, after that the other parameters arent shared instances anymore, but newly constructed objects.

**Comment by TomBZombie** [comment]
Can you provide the class constructor and the dice configuration?

**Comment by Steffen1996** [comment]
```
    public function __construct(Request $request, AuthenticatorInterface $authenticator)
    {
        $this->request = $request;
        $this->authenticator = $authenticator;
    }
```

```
{
    "*": {
        "shared": true
    },
    "PDO": {
        "constructParams" : [
            "mysql:dbname=testdb;host=localhost",
            "test",
            "12Xtest"
        ],
        "call": [
            [
                "setAttribute", [
                    17,
                    true
                ]
            ]
        ],
        "comment": "setAttribute 17 is PDO::Stringify_fetches"
    },
    "Application\\core\\middleware\\handler\\RouteHandler": {
        "substitutions": {
            "Application\\core\\route\\parser\\RouteParser": {
                "instance": "Application\\core\\route\\parser\\GetParamRouteParser"
            }
        }
    },
    "Application\\core\\auth\\RouteAuthenticator": {
        "substitutions": {
            "Application\\core\\auth\\AuthenticatorInterface": {
                "instance": "Application\\core\\auth\\AuthenticatorService"
            }
        }
    }
}
```
Request got used in many of the other classes, only here its a new instance

**Comment by TomBZombie** [comment]
I think i can see the issue. The way this *should* be achieved is using a named instance that turns off shared:


```
{
    "*": {
        "shared": true
    },
    "PDO": {
        "constructParams" : [
            "mysql:dbname=testdb;host=localhost",
            "test",
            "12Xtest"
        ],
        "call": [
            [
                "setAttribute", [
                    17,
                    true
                ]
            ]
        ],
        "comment": "setAttribute 17 is PDO::Stringify_fetches"
    },
    "Application\\core\\middleware\\handler\\RouteHandler": {
        "substitutions": {
            "Application\\core\\route\\parser\\RouteParser": {
                "instance": "Application\\core\\route\\parser\\GetParamRouteParser"
            }
        }
    },
    "Application\\core\\auth\\RouteAuthenticator": {
        "substitutions": {
            "Application\\core\\auth\\AuthenticatorInterface": {
                "instance": "$UniqueAuthenticatorService"
            }
        }
    }
    "$UniqueAuthenticatorService": {
        "shared":  false,
        "instanceOf":  "Application\\core\\auth\\AuthenticatorService"
        }
    }

}

```

However, when this happens `shared` gets set to an array containing true and false.  I have updated Dice, the latest git version will allow the configuration as above.

**Comment by Steffen1996** [comment]
Sorry next time i reread my own issue. The interface gets substitued without problem, as before - but the second parameter isn't shared anymore and i couldn't get it to shared, even with the new version and the provided dice configuration.

**Comment by TomBZombie** [comment]
Can you provide a bare-bones example of what you're trying to ask with skeleton classes (just names/constructors) along with Dice config and what you're expecting to happen so I can replicate your setup .

**Comment by Steffen1996** [comment]
Found the mistake. I tried to add my own instance to dice, so i added it as substitutions to *. These substitutions got overwritten by my own class-specific substitutions, because the array_merge not merges recursive. Don't know if this behavior is desirable, but I think in nearly every case i want to add my own instances to dices sharedInstances, because they got constructed by a static method or whatever - and this is (correct me if i'm wrong) the only option that i'm seeing right now, so i think either there should be a method to add my instance, or the array_merge should be array_merge_recursive.

**Comment by TomBZombie** [comment]
I don't think that would be a problem and it would make sense to merge_recursive the shared instances as long as it's possible to turn it off. If you did want to override a shared instance, you'd need to specifically set a `substitution` on that class which should have priority.

Todo: Write a test for this
