### ISSUE TITLE
Parse error: syntax error, unexpected '.' in ...\Dice.php on line 97

### ISSUE THREAD

**Issue by svratenkov** [Level-2/Dice#129]
You have 3 dots here:
```
return new $class->name(...$params($args, $share));
```

**Comment by TomBZombie** [comment]
This operator was introduced in PHP 5.6. There is a branch in this repository for older PHP versions, however I strongly recommend upgrading PHP as versions lower than 5.6 are no longer supported by PHP and may contain security issues: http://php.net/supported-versions.php
