### ISSUE TITLE
Preset Namespaces substitutes?

### ISSUE THREAD

**Issue by abayob** [Level-2/Dice#130]
Hey,

I would like to preset substitutes(aliases) of the classes that are often used for a cleaner syntax in my code:

Now:
```
$dice = new Dice\Dice;
$creator= $dice->create('Project\\Model\\Domain\\Creator');
```

What I would like to do:
```
$dice = new Dice\Dice;

// Adding some aliases for classes:
$dice->addRule('Creator', ['substitutions' => 'Creator' => 'Project\\Model\\Domain\\Creator']]);

$creator= $dice->create('Creator');
```

Is this currently possible?

**Comment by abayob** [comment]
After converting some code to using the Dice DI class, I am really wondering if I am doing stuff right.
The biggest issue is that most of my classes have constructor dependencies.

This translates to a lot of defined rules...

Before:
```
$oBankMutationQueries = new bankMutationQueries(new MsSqlSocket);
$oBankMutationsController = new bankMutationsController($oBankMutationQueries);
$oBankExportController = new BankExportController();

```

After:
```
$dice->addRule('IAT\\Model\\bankMutationsQueries', ['constructParams' => [$dice->create('IAT\\Model\\Database\\Sockets\\MsSqlSocket')]]);
$oBankMutationsQueries = $dice->create('IAT\\Model\\bankMutationsQueries');
$dice->addRule('IAT\\Controller\\bankMutationsController', ['constructParams' => [$oBankMutationsQueries]]);
$oBankMutationsController = $dice->create('IAT\\Controller\\bankMutationsController');
$oBankExportController = $dice->create('IAT\\Controller\\BankExportController');
```

Because of the namespaces I need to add to make it work, this is causing me to write ALOT more code.
I hope I am doing something wrong XD

**Comment by TomBZombie** [comment]
> I would like to preset substitutes(aliases) of the classes that are often used for a cleaner syntax in my code:

That's possible with `instanceof`:

```php
$dice->addRule('$ALIASNAME', ['instanceOf' => '\\Foo\\Bar\\Baz']);
$dice->create('$ALIASNAME'); //returns `\Foo\Bar\Baz` instance
```


Dice uses convention-over-configuration. In most cases you should just need to use type hints:

````php
namespace Project\Model;
class bankMutationsQueries {
 public function __construct(Database\Sockets\MsSqlSocket $socket) {
 }
}
```
This will create an instance of `bankMutationsQueries` and automatically inject a `Project\\Model\\Database\\Sockets\\MsSqlSocket` instance:

```php
$dice->create('bankMutationsQueries');
```

 In most cases you shouldn't need to manually specify every constructor argument.

**Comment by TomBZombie** [comment]
Also, remember that Dice is recursive and in a lot of case requires zero configuration:

```php
class A {
	public function __construct(B $b) {
		$this->b = $b;
	}
}


class B {
	public function __construct(C $c) {
		$this->c = $c;
	}
}

class C {
	public function __construct(D $d) {
		$this->d = $d;
	}
}

class D {}

//create the entire object graph without any configuration at all
$dice->create('A');
```

**Comment by abayob** [comment]
Thank you for your quick response!
I am currently converting a MVC application with +- 200 classes to using your Dice object. So a lot of questions and problems arise.

The biggest one I have ATM is all the interface typehinting.
As I have read, I can use the `substitutions` option to declare the currently used object and let Dice know what it must load.

Sadly this still needs an extra line of code per class instantiation, as there are many poly morphed classes every class can use.

Is there a simpler way for that, maybe with a rule wildcard (e.g. addRule('Project\\Model\\*', [somerule])?

**Comment by TomBZombie** [comment]
It depends exactly what you want to do, you can set up a global wildcard:

```php
$dice->addRule('*', ['substitutions' => ['\\SomeInterface' => '\\ConcreteClass']);
```

Now, anywhere that `\SomeInterface` is type hinted, it will be passed an instance of `\\ConcreteClass`. If you do need a different variant for each class, then yes, you will unfortunately need to provide configuration because there's no way for Dice to guess.

**Comment by abayob** [comment]
Again, thank you for your fast response.

It saves me a lot of writing with using `instanceOf`, so I will first fix that 👍

**Comment by garrettw** [comment]
In your second comment, you listed 5 lines of code that you are using now that you've added Dice.
As far as I can tell, you really only need the last two:
```php
$oBankMutationsController = $dice->create('Project\\Controller\\bankMutationsController');
$oBankExportController = $dice->create('Project\\Controller\\BankExportController');
```
Dice should be able to do everything else automatically.

Also, while the global wildcard '*' does work, partial wildcards ('Project\\Model\\*') do not.
