### ISSUE TITLE
Dice calls name() method on ReflectionClass instance

### ISSUE THREAD

**Issue by Kubitomakita** [Level-2/Dice#132]
Hi,

I'm trying to understand something. Here: https://github.com/Level-2/Dice/blob/master/Dice.php#L97 you are calling the `name()` method on ReflectionClass instance passing the list of callable arguments.

Please, could you give me a hint how is that possible? ReflectionClass doesn't have the `name()` method. Or is this part not used anymore and overlooked?

**Comment by maxwilms** [comment]
Hello!

Yes, this code is still in use. For example `BasicTest::testObjectGraphCreation()` fails if you comment this line out.

Nevertheless it really looks confusing! But `return new $class->name(...$params($args, $share));` does not call a method on the reflection class. Instead it gets the property `name` on the `ReflectionClass` and then calls the constructor on that class name. 

This would be a more obvious version of this line:
```
$className = $class->name;
return new $className(...$params($args, $share));
```

Hope this helps.

**Comment by Kubitomakita** [comment]
Wow, that's really optimized! Thanks for the answer @maxwilms, I can see what's going on now.

**Comment by garrettw** [comment]
Feel free to close this issue if your question has been answered sufficiently.
