### ISSUE TITLE
Use default parameter value if interface without available concrete class

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Dice#134]
```php
<?php
require 'vendor/autoload.php';

class A {
  function __construct(SomeInterface $c = null) {}
}
interface SomeInterface{}

$dice = new \Dice\Dice;



$dice->create('A'); 
```

Currently this gives the error `Cannot instantiate interface SomeInterface` because there is no substitution set. Ideally it should use the default value if no concrete class is provided.

**Comment by AriartWt** [comment]
Hi, 

I just tried you're snippet on the v3.0 and get the `Cannot instantiate interface SomeInterface` exception, is this the expected behaviour ? 
For my purprose, I changed the line 106-109 `return new $class->name;`

      <?php 
     //....
     else $closure = function () use ($class) {
            // No constructor arguments, just instantiate the class
	    return new $class->name;
     };
     //....

by ` return $class->isInterface() ? null : new $class->name;`, this solves the error but I wonder if this will not cause an unexpected behaviour on an other Dice's feature...

**Comment by TomBZombie** [comment]
Can you paste the constructor for the class where you're getting this error?

**Comment by AriartWt** [comment]
There is the constructor : 
    
     <?php 
    final class ValidToken implements IAccessRule
    {
        // some private var declarations ...
        public function __construct(
            ISession $session,
            INotifier $notifier,
            ?string $redirUrl = null,
            ?IMessage $message = null,
            ?string $sessionKey = null)
        {
            $this->_csrf = $session->get($sessionKey ?? "csrftoken");
            $this->_notifier = $notifier;
            $this->_redirUrl = $redirUrl ?? "users/login";
            $this->_message = $message ?? new Message(
                "Bad csrf token supplied !",
                MessageTypes::ERROR
            );
        }
       //methods...
    }

**Comment by TomBZombie** [comment]
The 3.0 branch was a few commits behind the 2.0 branch, I've created a 3.0-Dev-Rebase branch which has both sets of changes:

3.0 is a development branch and liable to change. To make JSON rules a bit tidier I also changed the `\Dice::INSTANCE` to `Dice::INSTANCE`. This will only affect you if you were using `instance` keys in rules defined in JSON format.

**Comment by AriartWt** [comment]
Thanks, i just updated to the new branch and it works like a charm.
