### ISSUE TITLE
Possible bug in substitutions?

### ISSUE THREAD

**Issue by Mprompt** [Level-2/Dice#136]
My first post ever on Github! :)

First of all I would like to say I really like Dice, easy to use and quick!

I have been running in to a strange problem with dice, the following rule works:
`$rule = ['instanceOf' => 'Foo', 'substitutions' => ['TestClass' => ['instance' => '\MyNameSpace\ExtendedTestClass']]];`

In this case ExtendedTestClass extends the TestClass. ExtendedTestClass is part of the MyNameSpace namespace. This situation works correct.

If I want to make TestClass part of the MyNameSpace namespace the substitution does not work anymore? The rule would be changed to:
`$rule = ['instanceOf' => 'Foo', 'substitutions' => ['\MyNameSpace\TestClass' => ['instance' => '\MyNameSpace\ExtendedTestClass']]];`

This does not seem to work and only loads TestClass instead of ExtendedTestClass.

A complete example of the non-working situation:
`namespace MyNameSpace {`

`  class TestClass {`
`    public function __construct() {`
`      echo "<br>Start TestClass (INCORRECT!)<br>";`
`    }`
`  }`
  
`  class ExtendedTestClass extends TestClass {`
`    public function __construct() {`
`      echo "<br>Start ExtendedTestClass (CORRECT!)<br>";`
`    }`
`  }`
`}`

`namespace {`
`  class Foo {`
`    public $tesclass;`
    
`    public function __construct(\MyNameSpace\TestClass $testclass) {`
`        $this->testclass = $testclass;`
`        echo "<br>FOO started<br>";`
`    }`
`  }`

 ` include("dice/dice.php");`
 ` $dice = new \Dice\Dice;`

 ` $rule = ['instanceOf' => 'Foo', 'substitutions' => ['\MyNameSpace\TestClass' => ['instance' => '\MyNameSpace\ExtendedTestClass']]];`

  `$dice->addRule('$route', $rule);`

  `$foo = $dice->create('$route');`
`}`

Maybe it's just me making a mistake but I personally think that substitutions does not consider namespaces.

**Comment by TomBZombie** [comment]
If you use:

```php
$rule = ['instanceOf' => 'Foo', 'substitutions' => ['MyNameSpace\TestClass' => ['instance' => '\MyNameSpace\ExtendedTestClass']]];
```

Removing the prefixing `\` does it work as intended?

**Comment by Mprompt** [comment]
Thank you for the quick reply! You where totally correct! I just found out the mistake myself...

**Comment by TomBZombie** [comment]
I'll update Dice to strip the preceding slash as this will likely catch other people out too.

**Comment by Mprompt** [comment]
Yes that would be great! You kind of presume it has to gave the preceding slash because it's also how a normal namespace is setup.
