### ISSUE TITLE
Dice.php:212 - Call to undefined method ReflectionType::getName()

### ISSUE THREAD

**Issue by wachulec** [Level-2/Dice#140]
Fatal error: Uncaught Error: Call to undefined method ReflectionType::getName() in _[...]_/vendor/level-2/dice/Dice.php on line 212

My php version 7.0.14

It seams Dice v. 3.0 is not compatible with php 7.0 but with php 7.1 and above according to contributed note of an _sofe2038 at gmail dot com_ at the http://php.net/manual/en/reflectiontype.tostring.php

**Comment by TomBZombie** [comment]
Thanks, I'e updated this.
