### ISSUE TITLE
Problem when using Interface for type hinting

### ISSUE THREAD

**Issue by mehdibo** [Level-2/Dice#142]
Here is a simple example:

```
class A
{
    public function __construct(InterfaceB $b, interfaceC $C)
    {
    }
}
```
And I have classes `B` and `C` implementing `interfaceB` and `interfaceC`
When I use:
```
$dice->create('A', [$dice->create('B'), $dice->create('C')]);
```

I get

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function A::__construct(), 0 passed in xx/xx/Dice.php on line 117 and exactly 2 expected in A.php on line 10

Am I using it wrong?

**Comment by TomBZombie** [comment]
Can you provide a complete example?

The following works as intended:


```php
class A
{
    public $b;
    public $c;

    public function __construct(InterfaceB $b, interfaceC $c)
    {
        $this->b = $b;
        $this->c = $c;
    }
}


interface InterfaceB {

}

interface InterfaceC {

}

class B implements InterfaceB {

}

class C implements InterfaceC {

}

$dice = new \Dice\Dice;
$a = $dice->create('A', [$dice->create('B'), $dice->create('C')]);

var_dump($a);

```
Output:

```
object(A)#9 (2) {
  ["b"]=>
  object(B)#4 (0) {
  }
  ["c"]=>
  object(C)#7 (0) {
  }
}

```

**Comment by mehdibo** [comment]
*feeling embarrassed* It was me not implementing the interfaces, I still have one problem (not a bug, but I don't know how to use Dice properly)

I have a configuration router (following your article), let's say I create a route like this for simplification:
```
$dice = new \Core\Dice();

$obj = $dice->create('\Core\Routing\Route', [$dice->create('\App\View\AView'), $dice->create('\App\Controller\AController')]);
```
And a view
```
class AView implements \Core\View
{
    private $model;

    public function __construct(\App\Model\AModel $model)
    {
        $this->model = $model;
    }

    public function output()
    {
        return $this->model->data;
    }
}
```
And a Controller
```
class AController implements \Core\Controller
{
    private $model;

    public function __construct(\App\Model\AModel $model)
    {
        $this->model = $model;
    }

    public function update()
    {
        $this->model->data = 'Updated';
    }
}
```

How can I make `\App\Model\AModel` a shared instance between the Model and the Controller?
I can create a rule for `\App\Model\AModel` using Dice, but what if I don't know what Model is used by the controller/view? how can I achieve that?

And thanks a lot.

**Comment by TomBZombie** [comment]
> but what if I don't know what Model is used by the controller/view? how can I achieve that?

As you're using type hints then Dice can work out which model needs to be instantiated.

You can use `shareInstances` to make it so an object is shared between everything below it in a given tree.

```php

$dice->addRule('\Core\Routing\Route', ['shareInstances' => [ '\App\Model\AModel']);

$obj = $dice->create('\Core\Routing\Route',[$dice->create('\App\View\AView'), $dice->create('\App\Controller\AController')]);
```

This works for a single route but if you want to handle different routes you need to do further configuration. You can use named instances to configure each route:


```php
$dice->addRule('$ARoute', [
    'shareInstances' => ['\App\Model\AModel'],
    'constructParams => [ 
                                        [\Dice\Dice::INSTANCE => '\App\View\AView'], 
                                        [\Dice\Dice::INSTANCE => '\App\Controller\AController']
      ]
]);

```

Then create the route with `$route = $dice->create('$ARoute');` This starts getting verbose and you may wish to consider using a JSON configuration file to handle your routes.

If you want to see how I handled this, take a look here: https://github.com/Level-2/Config-Router-ModuleJson which also implements basic REST.

Start with the json file so you can see what's going on: https://github.com/Level-2/Config-Router-ModuleJson/blob/master/sample-manifest.json

**Comment by mehdibo** [comment]
> As you're using type hints then Dice can work out which model needs to be instantiated.
> 
> You can use shareInstances to make it so an object is shared between everything below it in a given tree.

I can do that by passing `\App\Model\AModel` to the `shareInstances` rule, but what if the controller is using `\App\Model\BModel`, without me knowing which model the controller/view will use I can't create a rule for it.

Configuring each route is a lot, I'm planning to use a Convention-over-configuration router rather than a configuration router.

**Comment by mehdibo** [comment]
Thanks, I ended up creating a model interface and that worked. Great job!
