### ISSUE TITLE
Incomplete Dice::create() documentation?

### ISSUE THREAD

**Issue by DanMan** [Level-2/Dice#145]
https://github.com/Level-2/Dice/blob/f309ba36d1dd3128395c09274dcef3da2dfc8b0a/Dice.php#L78

The third parameter `$share` isn't explained on https://r.je/dice.html. What's that array supposed to hold? From the docblock it sounds more like it should be a Boolean.

**Comment by TomBZombie** [comment]
The third parameter is used for instances defined as `shareInstances` in a rule. If "shareInstances" is set to `A` and `B`, dice will create the `A` and `B` instances and store them in `$share`. This is then used when constructing the object.  There should be no reason to use this argument externally. Unfortunately PHP does not allow method overloading. 

Ideally we'd have this:


```php
public function create(string $name, array $args = []) {
//...
}

private function create(string $name, array $args = [], array $share = []) {
//...
}
```

In an early version of Dice, the `$share` argument didn't exist and shared instances were stored in `$args`. However, there are cases when using both `constructParams` (setting `$args`) and `shareInstances` in a rule didn't work as intended so we had to separate it out.

Todo: Fix the docblock
