### ISSUE TITLE
Method chaining/immutable objects/factories

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Dice#146]
At the moment Dice supports calling methods using `call`

```php
$rule => [

  'call' => [
         ['methodA', ['arg1', 'arg2'] ],
         ['methodB', ['arg1', 'arg2'] ]
];

```
This works in most cases but some objects require method chaining e.g.

```php
$request = new Request();

$request = $request->url('http://example.org')->method('POST')->body('foo=bar');
```

If `Request` is immutable and each method call returns a new `Request` instance, this cannot be expressed using Dice. The following code:

```php
$rules => [
  'Request' => [
  'call' => [
         ['url', ['http://example.org'] ],
         ['method', ['POST'] ],
         ['body', ['foo=bar'] ],
   ]
 ]
];


$dice->addRules($rules);
$dice->create('Request');
```

Will call the methods but the return value will be the original, empty `Request` instance as the return values of the method calls are never used. 

I propose a third, boolean, argument in the call array which is effectively "$useReturn` or `$chain`  where the object is replaced with the return value.

```php
$rules => [
  'Request' => [
  'call' => [
         ['url', ['http://example.org'], true],
         ['method', ['POST'], true ],
         ['body', ['foo=bar'], true ],
   ]
 ]
];


$dice->addRules($rules);
$dice->create('Request');
```

Each time a method is called, the `Request` object is replaced with the return value. 

This approach could also be useful, though less intuitive, for using existing factory methods. 

```php
$rules = [
	'$FooFactory' => [
		'instanceOf' => 'FooFactory',
		'call' => [
			['createFoo', [], true]
		]

	]
]
```

The code `$foo = $dice->create('$FooFactory')`  would call `FooFactory->createFoo()` and use the return value instead of returning the factory.

**Comment by TomBZombie** [comment]
I've added the code for this. I'll merge it if nobody has any better ideas of how to handle this.

**Comment by TomBZombie** [comment]
That's a fair point. I don't really like amending the method name as it seems untidy and it's always a pain to look up the exact syntax. 

Perhaps just allowing both `call` and `chain` to signify the difference?

```php
$rules => [
  'Request' => [
  'chain' => [
         ['url', ['http://example.org'] ],
         ['method', ['POST'] ],
         ['body', ['foo=bar'] ]
   ]
 ]
];
```

That might be more intuitive for method chaining but not very clear for calling factory methods.

**Comment by garrettw** [comment]
Agreed, that does look good for chaining. I can see how the meaning of "chain" might not be as clear for factories, but to me it's not horrible. Another option, albeit more verbose, could be "callWithReturn".

**Comment by TomBZombie** [comment]
Alternatively, what about a constant instead of a boolean?

```php
$rules => [
  'Request' => [
  'call' => [
         ['url', ['http://example.org'], Dice::CHAIN_CALL],
         ['method', ['POST'], Dice::CHAIN_CALL ],
         ['body', ['foo=bar'], Dice::CHAIN_CALL]
   ]
 ]
];
```

This might be better as it gives more flexibility. You could have another call at the end which isn't chained, usiung `chain` or `callWithReturn` keys, every call in the block has to be one or the other.

**Comment by garrettw** [comment]
This is true. Although it's probably the most verbose option, it might also be the most flexible.
