### ISSUE TITLE
Make Dice immutable (4.0 API)

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Dice#148]
There are a few minor gotchas with Dice due to it being mutable. The main one is the internal caching:

```php
$dice->addRule('Foo', ['shared' => true]);
$foo1 = $dice->create('Foo');
$dice->addRule('Foo', ['shared' => false]);
$foo2 = $dice->create('Foo');


var_dump($foo1 == $foo2); //TRUE
```

Here, you'd expect that the two instances are different. This goes for any rule, not just shared.

One solution is to manually empty the cache when `addRules` is called. But that could introduce even more bugs.

Consider the following:

```php

$dice = new \Dice\Dice();

$dice->addRule('DomDocument', 
    ['call' => [ ['loadHtmlFile', 'file.html'] ]);


function createBar(\Dice\Dice $dice) {
//Configure DomDocument for Bar to use:
$dice->addRule('DomDocument', 
    ['call' => [ ['loadHtmlFile', 'file2.html'] ]);

return $dice->create('Bar');
}


$doc1 = $dice->create('DomDocument');
$bar = createBar($dice);
$doc2 = $dice->create('DomDocument');

```

Should `$doc1` and `$doc2` be different here?  If `createBar` is called, the rule for `DomDocument` is replaced throughout the application. Probably not what was intended.

The solution is that Dice should be immutable. Yes, this means a backwards incompatible API change but it means that Dice is not prone to action at a distance when there are multiple references to it.
Each time `addRule` or `addRules` is called, a new Dice instance should be returned:

```php

$dice = new \Dice\Dice();

$dice = $dice->addRule('DomDocument', 
    ['call' => [ ['loadHtmlFile', 'file.html'] ]);


function createBar(\Dice\Dice $dice) {
//Configure DomDocument for Bar to use:
$dice = $dice->addRule('DomDocument', 
    ['call' => [ ['loadHtmlFile', 'file.html'] ]);

return $dice->create('Bar');
}


$doc1 = $dice->create('DomDocument');
$bar = createBar($dice);
$doc2 = $dice->create('DomDocument');
```
The original instance is never changed and the problems are avoided.

**Comment by garrettw** [comment]
Glad to see this being addressed. This is part of the reason I had started making my own DIC.

**Comment by TomBZombie** [comment]
Dice won't be able to be immutable in the strictest sense (see https://r.je/immutability-encapsulation-schrodingers-immutability.html ) but to make it look immutable externally I don't think we need to do much.

Shared instances need to be copied across between dice instances. 

Consider this:

```
class Bar {

public function __construct(PDO $pdo) {} 

}


$dice = $dice->addRule('PDO', ['shared' => true]);
$pdo = $dice->create('PDO');

function createBar(\Dice\Dice $dice) {
$dice = $dice->addRule('Foo', []);
return $dice->create('Bar');
}
```

I would expect `Bar` to be given the existing shared `$pdo` instance. However, it should also be able to configure its own. 

To achieve that I think addRule needs to clear the set instance and cache when a rule is added or overwritten

```
    	unset($this->instances[$name], $this->cache[$name]);

```

**Comment by garrettw** [comment]
The new `addRules()` fails with the following test I devised:
```php
	public function testSetMultipleRules() {
		$rules = [
			'*' => ['shared' => true],
			'TestCallImmutable' => ['shared' => true],
		];
		$dice = $this->dice->addRules($rules);

		$rule = $dice->getRule('*');
		$this->assertEquals($rule['shared'], true);
		$rule = $dice->getRule('TestCallImmutable');
		$this->assertEquals($rule['shared'], true);
	}
```

The following code for `addRules()` makes the above test pass:
```php
	public function addRules($rules): self {
		if (is_string($rules)) $rules = json_decode(file_get_contents($rules), true);
		$dice = $this;
		foreach ($rules as $name => $rule) $dice = $dice->addRule($name, $rule);
		return $dice;
	}
```

**Comment by TomBZombie** [comment]
Yes, you're right, I've implemented your change.

**Comment by garrettw** [comment]
Actually it looks like it wasn't implemented quite right. Line 3 of the function body says `$dice = $dice->addRule...` but [your code](https://github.com/Level-2/Dice/blob/master/Dice.php#L56) says `$dice = $this->addRule...`
I can easily see how that would cause #156.
