### ISSUE TITLE
YAML config loader?

### ISSUE THREAD

**Issue by garrettw** [Level-2/Dice#150]
Dice currently supports JSON and XML configs, which is understandable because PHP already includes the relevant parsers. A lot of modern projects seem to like using YAML config files, and it's true that the syntax is more readable and terse -- so given the drawback that parsing YAML would involve [either a PECL extension or a library dependency](https://stackoverflow.com/questions/294355/php-yaml-parsers), what are your thoughts about supporting that format? I think a YAML loader could be included that would sniff for one or both of those solutions and fail nicely if neither exist.

**Comment by TomBZombie** [comment]
A better method might be to create a `Dice-yaml` package which had a dependency on `Dice` and whichever yaml package can be installed through composer.

**Comment by garrettw** [comment]
Agreed, XML has always seemed to me to be mostly the purview of the Microsoft development world.
I guess making a separate package would be fine.

**Comment by TomBZombie** [comment]
Also, we shouldn't really need specific loaders now that Dice supports `addRules`. You should be able to use your favourite YAML parser and do this:

```php
$dice = $dice->addRules(yaml_parse('rules.yaml'));
```
Which is one of the reasons JSON is better than XML, you can more easily create a native data structure.

**Comment by garrettw** [comment]
Indeed, fair point.
