### ISSUE TITLE
Probable bug in substitutions

### ISSUE THREAD

**Issue by garrettw** [Level-2/Dice#151]
On [line 37](https://github.com/Level-2/Dice/blob/master/Dice.php#L37):
```php
if (isset($rule['substitutions'])) foreach($rule['substitutions'] as $key => $value) $rule[ltrim($key,  '\\')] = $value;
```
It's trimming the backslash off of the keys in `$rule['substitutions']` BUT it's saving them back to `$rule` itself, not `$rule['substitutions']`.

Corrected code:
```php
if (isset($rule['substitutions'])) foreach($rule['substitutions'] as $key => $value) $rule['substitutions'][ltrim($key,  '\\')] = $value;
```

**Comment by TomBZombie** [comment]
well spotted, I'm surprised nobody caught this sooner.

**Comment by garrettw** [comment]
Me too.
