### ISSUE TITLE
Degraded performance since 4.0

### ISSUE THREAD

**Issue by kocsismate** [Level-2/Dice#155]
Hey,

When running my container benchmark with Dice 4.0, I noticed that your lib is much-much slower than before, for instance the last test takes __minutes__ for Dice. I guess it could be related to the immutability change, because since I downgraded to Dice 3.0, the performance is normal.

Can you confirm the issue? Or is it just a problem with the configuration? Could you review if the config is still ok here: https://github.com/kocsismate/php-di-container-benchmarks/blob/master/src/Container/Dice/AbstractDiceTest.php ?

**Comment by TomBZombie** [comment]
Sorry I'm on my phone so can't include any code but the issue is that the test is not updated for the new api. In this test the other containers will be returning the same instance each call while dice returns a new instance each time, which is why it's comparatively slower

**Comment by kocsismate** [comment]
Ah, I see it now in the Read me, thanks for the info!

**Comment by TomBZombie** [comment]
I'm surprised at how dice is so comparatively slow in some tests now. Specifically how any other container can be any faster in test 5. Literally the only code Dice runs in the function is this:

```
if (!empty($this->instances[$name])) return $this->instances[$name];
```

A simple array lookup. I'll see if I can tweak it but I'm surprised other containers which must have similar logic (if an instance exists, return it) can be 50% faster.

**Comment by kocsismate** [comment]
This is a very interesting observation! I also spent many hours with optimizing these 2 lines, so here are two things what I believe will make the performance better:

- Using `isset()` is faster than `empty()` because there is no overhead for calling a function as `isset()` is a language construct. But I remember to hear somewhere that `array_key_exists()` can be even faster in the future (unfortunately I can't find the reference anymore :( )
- Using `??` is even faster, Zen and Symfony gained their speed advantage because of this optimization.

It looks like this in the case of Symfony:
```
return $this->services[$id]
            ?? $this->services[$id = $this->aliases[$id] ?? $id]
            ?? ('service_container' === $id ? $this : ($this->factories[$id] ?? array($this, 'make'))($id, $invalidBehavior));
```

And here is the same with Zen:
```
return $this->singletonEntries[$id] ?? $this->{static::$entryPoints[$id] ?? "throwNotFoundException"}($id);
```

I would be also very curious how much these help for Dice, so ping me when I can rerun the benchmarks! :)

BTW: that's why I don't respect much the test suite 5-6, because they only measure a very tiny part of the overall service location process. But still, they can be very useful when optimizing the `get()`/`create()` method itself.

**Comment by TomBZombie** [comment]
By the way, my previous point still stands: Your benchmarks don't give a complete picture because they don't fully measure startup time. If a container has 30 classes, 30 classes have to be loaded from the opcache into memory. Whereas a container with a single class, only one class has to be loaded from the opcache. I'm not sure how much of a difference it would make  (if any, I'm not sure how the opcache works internally) but this time is not currently accounted for in your tests. 

To accurately test, for each container you'd need to:

- Clear the opcache (in case PHP loads the complete opcache every time it starts e.g. loading Symfony classes during a Zen test)
- Run the test once without benchmarking it to generate the opcache
- Run the benchmark and everything will still come from the opcache but measure the time it takes for the PHP process to run and exit instead of the time from the point PHP starts running the first line of PHP code as happens at the moment.

This would measure the actual startup time/overhead/memory and It would also allow you to include Phalcon in the tests.

**Comment by TomBZombie** [comment]
@kocsismate It appears my theory is correct and PHP does load the complete opcache. Your memory tests are flawed: Each time it has all the other container's loaded in the opcache.

This invalidates the timing benchmarks but as a quick dirty test add `opcache_reset();` to the top of `public/index.php` 

Doing this, Dice goes from 148% memory in test 5/6 to 96%. Presumably, because the classes for all the other containers are not already loaded into memory from the opcache.

As a very quick fix for the tests, that won't invalidate the speed benchmarks do this, change `WebBenchmarkContext` to this:

```php
<?php
declare(strict_types=1);

namespace DiContainerBenchmarks\Benchmark;

class WebBenchmarkContext implements BenchmarkContextInterface
{
    /**
     * @var string
     */
    private $benchmarkUrl;

    public function __construct(string $benchmarkUrl)
    {
        $this->benchmarkUrl = $benchmarkUrl;
    }

    private function runTest(int $number, string $container, int $iterations, string $testType): string
    {
        $ch = curl_init();
        curl_setopt(
            $ch,
            CURLOPT_URL,
            $this->benchmarkUrl . "?test_suite=$number&container=$container&iterations=$iterations&test_type=$testType"
        );
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        $output = curl_exec($ch);
        curl_close($ch);

        return $output ? $output : "";
    }

    public function getTestOutput(int $number, string $container, int $iterations, string $testType): string
    {   
        //Clear the opcache to remove cached classes from previous container's tests
        opcache_reset();
        //Run the test once to generate the opcache for this container's classes
        $this->runtest($number, $container, 1, $testType);

        //Now run the actual test where classes are loaded from the opcache and the opcache only contains the classes being tested
        return  $this->runtest($number, $container, $iterations, $testType);

    }
}

```

Currently this doesn't work because the opcache is not enabled in the non-web php process that runs the test but this will at least give fairer results for the memory tests.

**Comment by kocsismate** [comment]
@TomBZombie You are right, PHP's type checks also affect those test results. People at Symfony also realized it a while ago: https://github.com/symfony/symfony/pull/25474, unfortunately I forgot to mention this factor in my previous comment. :S (I's a bit sad btw that constants also slow the code down. :D)

And the topic about opcache is also very interesting, thanks for thinking about it! After a quick check though, I don't agree to you in every aspect, but I'll try to read your comments more thoroughly, and write an answer a bit later.

But what I know for sure is that `opcache_reset()` does never work in the CLI when you want to reset the cache of the web server: https://ma.ttias.be/how-to-clear-php-opcache/ That's why `opcache_reset()` should be added to a newly added `public/opcache_reset.php` file instead, and then `Benchmark` class can call it when needed.

**Comment by TomBZombie** [comment]
I've updated your tests to do this:

```php
<?php
declare(strict_types=1);

namespace DiContainerBenchmarks\Benchmark;

class WebBenchmarkContext implements BenchmarkContextInterface
{
    /**
     * @var string
     */
    private $benchmarkUrl;
    private $overheadTime;

    public function __construct(string $benchmarkUrl)
    {
        $this->benchmarkUrl = $benchmarkUrl;
    }

    private function calcOverheadTime()
    {
        if (!$this->overheadTime) {
            //clear the opcache so it's not included in the overhead time
            $this->httpRequest(str_replace('index.php', 'opcache_reset.php', $this->benchmarkUrl));

            //Make 1000 requests and take an average
            $totalTime = 0;
            $runs = 1000;
            echo "Calculating request overhead time average $runs runs\n";

            for ($i = 0; $i < $runs ; $i++) {
                $t1 = microtime(true);
                $this->httpRequest(str_replace('index.php', 'blank.php', $this->benchmarkUrl));
                $t2 = microtime(true);
                $totalTime += ($t2 - $t1);
            }

            $this->overheadTime = $totalTime/$runs;
            echo 'Average overhead time:' . $this->overheadTime . "\n";
        }

        return $this->overheadTime;
    }

    private function httpRequest($url)
    {
        $ch = curl_init();
        curl_setopt(
            $ch,
            CURLOPT_URL,
            $url
        );
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $output = curl_exec($ch);
        curl_close($ch);

        return $output;
    }

    public function getTestOutput(int $number, string $container, int $iterations, string $testType): string
    {

        //Calculate average HTTP request overhead to remove it from the test
        $overhead = $this->calcOverheadTime();

        //Clear the opcache to remove cached classes from previous container's tests
        $this->httpRequest(str_replace('index.php', 'opcache_reset.php', $this->benchmarkUrl));

        $t1 = microtime(true);
        //Run the test once to generate the opcache for this container's classes
        $this->httpRequest($this->benchmarkUrl . "?test_suite=$number&container=$container&iterations=1&test_type=$testType");

        $t2 = microtime(true);

        $time = $t1 - $t2 - $overhead;
        //Now run the actual test where classes are loaded from the opcache and the opcache only contains the classes being tested
        $output = $this->httpRequest($this->benchmarkUrl . "?test_suite=$number&container=$container&iterations=$iterations&test_type=$testType");

        if (!$output) return "";

        if ($testType == 'warm') return $output;

        $result = json_decode($output);
        $result->time = $time;
        return json_encode($result);
    }
}

````

blank.php is just a blank php file. My code is inefficient and needs improvement but will give much closer results to a real production server.

**Comment by TomBZombie** [comment]
Results of the above attached. As you can see, the results change dramatically if you actually run a real world test. 

I need to better calculate the average overhead time because a few slow requests result in a negative score for the containers where overhead time is actually greater than the test time.

[benchmark.zip](https://github.com/Level-2/Dice/files/2683604/benchmark.zip)

**Comment by TomBZombie** [comment]
Better calculation of overhead time and updated results:

```php
<?php
declare(strict_types=1);

namespace DiContainerBenchmarks\Benchmark;

class WebBenchmarkContext implements BenchmarkContextInterface
{
    /**
     * @var string
     */
    private $benchmarkUrl;
    private $overheadTime;

    public function __construct(string $benchmarkUrl)
    {
        $this->benchmarkUrl = $benchmarkUrl;
    }

    private function calcOverheadTime()
    {
        if (!$this->overheadTime) {
            //clear the opcache so it's not included in the overhead time
            $this->httpRequest(str_replace('index.php', 'opcache_reset.php', $this->benchmarkUrl));

            //Make 1000 requests and take an average
            $totalTime = 0;
            $runs = 1000;
            echo "Calculating request overhead time average $runs runs\n";

            $times = [];
            for ($i = 0; $i < $runs ; $i++) {
                $t1 = microtime(true);
                $this->httpRequest(str_replace('index.php', 'blank.php', $this->benchmarkUrl));
                $t2 = microtime(true);
                $times[] += ($t2 - $t1);
            }
            asort($times);

            //Only take the top 50% of results to ignore any unusually slow requests
            $times = array_slice($times, 0, (int) $runs/2);
            $totalTime = array_sum($times);

            $this->overheadTime = $totalTime/$runs;
            echo 'Average overhead time:' . $this->overheadTime . "\n";
        }

        return $this->overheadTime;
    }

    private function httpRequest($url)
    {
        $ch = curl_init();
        curl_setopt(
            $ch,
            CURLOPT_URL,
            $url
        );
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $output = curl_exec($ch);
        curl_close($ch);

        return $output;
    }

    public function getTestOutput(int $number, string $container, int $iterations, string $testType): string
    {

        //Calculate average HTTP request overhead to remove it from the test
        $overhead = $this->calcOverheadTime();

        //Clear the opcache to remove cached classes from previous container's tests
        $this->httpRequest(str_replace('index.php', 'opcache_reset.php', $this->benchmarkUrl));


        //Run the test once to generate the opcache for this container's classes
        $this->httpRequest($this->benchmarkUrl . "?test_suite=$number&container=$container&iterations=1&test_type=$testType");


        //Now run the actual test where classes are loaded from the opcache and the opcache only contains the classes being tested
        $t1 = microtime(true);
        $output = $this->httpRequest($this->benchmarkUrl . "?test_suite=$number&container=$container&iterations=$iterations&test_type=$testType");
        $t2 = microtime(true);

        $time = $t2 - $t1 - $overhead;

        if (!$output) return "";

        if ($testType == 'warm') return $output;

        $result = json_decode($output);
        $result->time = $time;
        return json_encode($result);
    }
}
```


This is a much fairer test because it's actually measuring a production like environment. The original test heavily favoured compiled containers (as seen in the results) because the time taken to load the compiled code is not taken into consideration during the tests.


[benchmark.zip](https://github.com/Level-2/Dice/files/2683619/benchmark.zip)


(sorry about the zip files, github doesn't allow attaching HTML)

**Comment by TomBZombie** [comment]
Hmm, actually this isn't quite right. How can I make a HTTP request to other files? BENCHMARK_URL is benchmark-nginx but I can't seem to access benchmark-nginx/opcache_reset.php
