### ISSUE TITLE
Proposal: wrap object creation in try/catch block to prevent stack trace leaking PDO credentials

### ISSUE THREAD

**Issue by moozeek** [Level-2/Dice#157]
Hi,

when instantiating a PDO connection you'd normally wrap it in a try / catch block to prevent it printing the DB credentials to the stack trace if the connection fails.

With Dice's auto-wiring this is not possible, so we get the credentials leaked into sthe stack trace:

> 	**Message:**
>     SQLSTATE[HY000] [2002] Connection failed: SQLSTATE[HY000] [2002] Connection refused. 
>      [\vbox\htdocs\test\app\vendor\level-2\dice\Dice.php:125] 
> 	
> 	**Trace:** 😱 
>     [/vbox/htdocs/test/app/vendor/level-2/dice/Dice.php:125] PDO-&gt;__construct('**mysql:host=127.0.0.1;dbname=test','root','password**',...
>     [/vbox/htdocs/test/app/vendor/level-2/dice/Dice.php:133] Dice\Dice-&gt;Dice\{closure}([],[])\n
>    ...

So I suggest adding a try  / catch block to Dice's instantiating method `getClosure()` to catch the PDO exception (and other runtime exceptions as well) and turn it into a runtime exception instead:

```php
private function getClosure(string $name, array $rule) {
...
else if ($params) $closure = function (array $args, array $share) use ($class, $params) {
...
try {
     return new $class->name(...$params($args, $share));
 } catch (\Exception $e) {
     throw new \RuntimeException($class->name . ' : ' . $e->getMessage());
    }
};
```

This way we'd get a meaningful error message but without leaking PDO the DB connection credentials to the stack trace:

> **Message:**
>     Controllers\Web\TestController : Models\UserModel : PDO : SQLSTATE[HY000] [2002] Connection failed: SQLSTATE[HY000] [2002] Connection refused. 
>     [\vbox\htdocs\test\app\vendor\level-2\dice\Dice.php:129]
> 
> **Trace:** 😎
>     [/vbox/htdocs/test/app/vendor/level-2/dice/Dice.php:101] Dice\Dice-&gt;Dice\{closure}([],[])\n
>     ...

What do you think?

**Comment by TRPB** [comment]
I'm open to doing this but I'm not convinced this is the best approach. 

Firstly, you shouldn't be displaying errors in production where leaking the password actually matters. Secondly, can't you just try/catch the dice->create() call? Thridly, this removes the parameters for the stack trace everywhere, for debugging they may sometimes be useful.

**Comment by moozeek** [comment]
You are right Tom. Somehow it didn't occur to me or it wasn't obvious to simply try/catch dice->create() 🤭
That way I also can control what and when I want it on the stack trace. So that solves for me. 

Sorry for bothering you and thanks a lot for your work, it's much appreciated!

**Comment by garrettw** [comment]
Feel free to close the isue then
