### ISSUE TITLE
Factory gets injected instead of instance for shared instances

### ISSUE THREAD

**Issue by someone635** [Level-2/Dice#165]
Hi,

I've got this rule to create ServerRequests from a ServerRequestFactory:

```php
ServerRequest::class => [
        'shared' => true,
        'instanceOf' => ServerRequestCreator::class,
        'call' => [
            [
                'fromGlobalsAndParsedBody',
                [
                    $_SERVER,
                    $_GET,
                    $_POST,
                    $_COOKIE,
                    $_FILES,
                    $phpinput,
                    $body->parse()
                ],
                Dice::CHAIN_CALL
            ]
        ]
    ]
```

Now if I call $serverRequest = $di->create(ServerRequest::class); it works fine, I get my server request.

Later on, though, I try to instantiate a Controller which depends on a ServerRequest instance:

```php
class SomeController
{
    public function __construct(
        ServerRequest $request,
    ) {
        $this->request = $request;
    }
```

I get this exception: Uncaught TypeError: Argument 1 passed to SomeController::__construct() must be an instance of ServerRequest, instance of ServerRequestCreator given

It thus injects the factory (ServerRequestCreator) instead of the instance.
This only occurs when 'shared' is true. When 'shared' is false the ServerRequest is injected as expected.

**Comment by someone635** [comment]
Oh and if I do:

$serverRequest = $di->create(ServerRequest::class)
$serverRequest = $di->create(ServerRequest::class)

The first one is a serverRequest and the second one is a serverRequestCreator

**Comment by TRPB** [comment]
Can you try the latest commit? I just added an addition that should fix this.

**Comment by someone635** [comment]
It works for me, thank you!
