### ISSUE TITLE
Version 4 and immutability

### ISSUE THREAD

**Issue by MichielioZ** [Level-2/Dice#166]
First a little nitpicking: the current version is still 3.0 in the code...
My second issue is with the immutability of Dice in version 4.
I have a little "framework" (more of an architectural boilerplate) and extended Dice (v3.0) to fit my needs for this. I tried upgrading to version 4 and this (obviously) failed, due to the changes made.
As it turns out, it is (mostly) due to the immutable nature of version 4.
So then I started wondering what the reasoning was behind making Dice immutable...
Quoting your readme: "This avoids issues surrounding mutability where a Dice instance is passed around the application and reconfigured."
This leads me to think you made the change for people that are passing around Dice and configuring it everywhere in their code ?! Didn't those people just use Dice wrongly to begin with ?

**Comment by TRPB** [comment]
Thanks for the point about the code, I'll bump the version number.

The problem is when you do this:

```php
$dice->create('Foo');

doSomethingWithDice($dice);

$dice->create('Bar');
```

The problem is, there is no way to know whether `doSomethingWithDice` has made any changes to  the Dice instance. This alone makes the code more difficult to understand and follow. 

The problem is, this code:

```php
$dice->create('Foo');

// doSomethingWithDice($dice);

$dice->create('Bar');
```

may or may not have the same result as the code above depending on what the function is doing.

Instead, by making the object immutable, such behaviour has to be explicit:

```php
$dice->create('Foo');

$dice = doSomethingWithDice($dice);

$dice->create('Bar');
```

Looking at this code, I can immediately tell that the function makes changes to the configuration. This doesn't just affect Dice but any object.

With an immutable instance, the following will always have the same result:


```php
$dice->create('Foo');

doSomethingWithDice($dice);

$dice->create('Bar');
```

or

```php
$dice->create('Foo');

// doSomethingWithDice($dice);

$dice->create('Bar');
```

**Comment by MichielioZ** [comment]
I understand what your saying and you've certainly tackled the problem.
I just have a problem with the problem ;-)
In my opinion the function 'doSomethingWithDice' (or a class for that matter) should never get Dice as an argument...

**Comment by TRPB** [comment]
There are times when it's useful. Take a look here as an example: https://r.je/mvc-php-router-dependency-injection

Or a proper version of this code:
https://github.com/Level-2/Config-Router-ModuleJson/blob/master/ModuleJson.php

**Comment by MichielioZ** [comment]
Ah yes, the 'router' problem.
Again, just my opinion, but couldn't you just let the router return the rules it wants to apply as an array ?
I've personally never had much use for a "traditional" PHP router, I use a "processor" to process all input, but that is besides the point, sorry

**Comment by MichielioZ** [comment]
After my previous comment, I feel like explaining my use case. So hopefully this explains my little setup: (it's a cut down version, so hopefully you can fill in the blanks)
```php
// Container adds (among other things) a method called 'alias'
class Container extends Dice\Dice {}

$container = new Container($config);

while ($container->has('process') {
    extract($container->process()); // gives $alias, $input
    $container->alias($alias);
}

$data = [];
if ($container->has('persist')) $data['persist'] = $container->persist($input['persist']);
if ($container->has('collect')) $data['collect'] = $container->collect($input['collect']);

$container->respond($data);
```
