### ISSUE TITLE
Parent class substitution

### ISSUE THREAD

**Issue by Loki3000** [Level-2/Dice#170]
Hi there!
I want to substitute class created by dice:

```
class A {}
class B extends A {}

$dice = new \Dice\Dice;
//somewhere in config I define to use B instead of A everywhere
$dice->addRule('*', ['substitutions' => ['A'=>'B']]);

$a=$dice->create('A'); //expected B, but it's A
```

It is bug or not? And how to solve it now?

**Comment by TRPB** [comment]
Substitutions only affect classes that are injected so this will work:


```php
class A {}
class B extends A {}

class RequiresB {
    public function __construct(A $a) {
        var_dump($a); //B instance
    }
}


$dice = new \Dice\Dice;
//somewhere in config I define to use B instead of A everywhere
$dice->addRule('*', ['substitutions' => ['A'=>'B']]);

$a=$dice->create('RequiresA'); 
```

If you need to do this, you can use `instanceOf` 

```
$dice->addRule('A', ['instanceOf' => 'B']);
$b = $dice->create('A');
```

Though I wouldn't recommend this as it breaks the principle of least surprise. Instead, used a named instance so it's clear to anyone looking at the code:


```
$dice->addRule('$SomeInstance', ['instanceOf' => 'B']);
$b = $dice->create('$SomeInstance');
```

**Comment by Loki3000** [comment]
Be consistent: 'substitutions' breaks the principle of least surprise in same way, but at some level deeper:)
Thanks for help!

**Comment by TRPB** [comment]
> Be consistent: 'substitutions' breaks the principle of least surprise in same way, but at some level deeper:)

That's true, but normally the type hint in such a situation would be an interface as inheritance is usually a bad idea, so you'd be expecting an instance of something other than what was type hinted when looking at the constructor.
