### ISSUE TITLE
PSR-11 Compliant

### ISSUE THREAD

**Issue by pattisahusiwa** [Level-2/Dice#173]
Would you consider changing Dice API to follow PSR-11 (https://www.php-fig.org/psr/psr-11/) guidelines?

**Comment by garrettw** [comment]
Dice itself will not change, as the container's API is part of what makes each one different from the next.

However, Tom has released a compatibility package targeting what you're talking about.
See https://github.com/TRPB/Dice-Interop

**Comment by sdotb** [comment]
Is actually the interop fully compatible with PSR-11?

**Comment by garrettw** [comment]
It's not hard to determine that for yourself, but... yes, it is compatible. PSR-11 is not a complicated spec.

**Comment by pattisahusiwa** [comment]
> Is actually the interop fully compatible with PSR-11?

Yes. However, instead of
````php
return $this->dice->create($id);
````
you should write something like this
````php
try {
	return $this->dice->create($id);
} catch (Throwable $th) {
	throw new ContainerException($th->getMessage(), $th->getCode(), $th);
}
````
