### ISSUE TITLE
Wildcards in rules

### ISSUE THREAD

**Issue by vasikgreif** [Level-2/Dice#185]
Is it possible to use wildcards in the rules? Ie., I would like to have all classes under a specific namespace (ie. `MyApp\Managers`) `shared`, without having to explicitely define every single class in the config. 

Is this possible somehow?

**Comment by vasikgreif** [comment]
Any idea on this one please?

**Comment by TRPB** [comment]
At the moment, it's not possible to do this and the performance overhead would be quite large as every single time an instance is created/retrieved it would need to find the rule in a wildcard manner.

If the majority of your classes are shared, you can set `shared` as the default rule and then set `shared` to false for the ones that are not.

**Comment by vasikgreif** [comment]
Thanks, will do that.
