### ISSUE TITLE
Shared chain call

### ISSUE THREAD

**Issue by pattisahusiwa** [Level-2/Dice#188]
I've rules like this.

````json
{
  "Factory": {
    "shared": true
  },
  "$object": {
    "instanceOf": "Factory",
    "call": [
      [
        "getObject",
        [],
        "Dice::CHAIN_CALL"
      ]
    ]
  }
}
````

Calling `$dice->create('$object')` or `$dice->create('Factory')` multiple times will return the same object as expected.

The `Factory` also needs to access the same instance as defined in `$object`. However, in the code below `$objectA` and `$objectB` point to different instances.
````php
$objectA = $dice->create('$object');

$factory = $dice->create('Factory');
$objectB = $factory->getObject();
````

Can this feature be added to Dice? So, both `$objectA` and `$objectB` point to the same instance.

**Comment by solleer** [comment]
Since `$object` is considered a different instance of `Factory` then it will not be the same. If they were shared then you would never be able to define a different version of the object, for example if you had `PDO` and `$otherPDO`.

**Comment by pattisahusiwa** [comment]
Honestly, I've rules like this
````json
{
  "$objectA": {
    "instanceOf": "Factory",
    "call": [
      [
        "getObjectA",
        [],
        "Dice::CHAIN_CALL"
      ]
    ]
  },
  "$objectB": {
    "instanceOf": "Factory",
    "call": [
      [
        "getObjectB",
        [],
        "Dice::CHAIN_CALL"
      ]
    ]
  }
}
````
Both rules require the same instance, so this rule is added. However, current implementation doesn't allow this use case.
````json
  "Factory": {
    "shared": true
  }
```` 



> If they were shared then you would never be able to define a different version of the object, for example if you had `PDO` and `$otherPDO`.

We can use something like this
````json
{
  "$otherPDO": {
    "instanceOf": "PDO",
    "shared": false
  }
}
````

**Comment by solleer** [comment]
> We can use something like this

I just remembered that there is the `inherit: false` syntax to prevent the issue I was describing.

I think the main issue here is that `$objectA` and `$objectB` are not actually instances of `Factory` but instead something created by it. In my experience the config `{"Dice::INSTANCE" : ["Factory", "getObjectA"]}` would return the same `objectA` instance every time it is retrieved. This issue is that the `instanceOf` and `call` method of getting `objectA` is different in the way it processes it.

**Comment by pattisahusiwa** [comment]
Suppose I've
````php
$factory = new Factory();

$classA = new ClassA($factory->getObjectA());
$classB = new ClassB($factory->getObjectB());

$classC = new ClassC($classA, $classB);
````

I need to create `$classC` directly without create `$factory`, `$classA`, and `$classB` manually.
````php
$classC =  $dice->create('ClassC');
````

Can dice be used for this use case?

**Comment by TRPB** [comment]
I don't think this is currently possible with json rules, but you can do it with closures: 

```php
$dice->addRules([
	'classC' => [
		'substitutions' => [
			'ClassA' => [\Dice\Dice::INSTANCE => function() use ($factory) {
			            return $factory->getObjectA();
			}],
			'ClassB' => [\Dice\Dice::INSTANCE => function() use ($factory) {
			            return $factory->getObjectB();
			}]
		]
	]
]);
```

Factory and DIC are different approaches to the same problem. With DIC you generally don't need factories as the same can usually be achieved in the container and all the factory is really doing is providing functionality already provided by the container:


```json
{
	"ClassA": {
		//rules for objectA instantiation (currently in your factory)
	},
	"ClassB": {
		//rules for objectB instantiation (currently in your factory)
	}
}
```

```php

class ClassC {
	public function __construct(ClassA $objectA, ClassB $objectB) {

	}

}


$dice->create('ClassC');
```

**Comment by pattisahusiwa** [comment]
> > We can use something like this
> 
> I just remembered that there is the `inherit: false` syntax to prevent the issue I was describing.
> 
> I think the main issue here is that `$objectA` and `$objectB` are not actually instances of `Factory` but instead something created by it. In my experience the config `{"Dice::INSTANCE" : ["Factory", "getObjectA"]}` would return the same `objectA` instance every time it is retrieved. This issue is that the `instanceOf` and `call` method of getting `objectA` is different in the way it processes it.

The main issue is `objectA` is initialized inside factory and is passed into `objectB` by the factory itself. So, when `objectA` is changed, `objectB` has the state too.

This use case is similar to `Aura/Router`. `Map`, `Matcher`, and `Generator` can be retrieved from `RouterContainer`. However, `Matcher` and `Generator` point to the same `Map` that reside in the container.

**Comment by solleer** [comment]
@pattisahusiwa If you know the class you are passing it into then it is possible currently.
@TRPB Using `Dice::INSTANCE` will allow passing the same instance here because [`Dice::INSTANCE` calls `create`](https://github.com/Level-2/Dice/blob/cbcc42205b8ce9fcd04b9fa60fc3da409c7d3fea/Dice.php#L182) then calls the methods on it when the `instanceOf` and `call` method does not create the same factory first.

Example code that I believe should work here (because I have had this same issue before)
```
{
    "Factory": {
        "shared": true
    },
    "ClassC" : {
        "constructParams" : [
            {"Dice::INSTANCE" : ["Factory", "getClassA"]},
            {"Dice::INSTANCE" : ["Factory", "getClassB"]},
        ]
    }
}
```

**Comment by pattisahusiwa** [comment]
@TRPB @solleer thank you. It works.
