### ISSUE TITLE
How to share a substitution

### ISSUE THREAD

**Issue by garrettw** [Level-2/Dice#191]
I've run into a situation that has me a bit confused. Here's the minimal case of what I've written:
```php
$app = (new Dice())->addRules([
    '*' => [
        'substitutions' => [
            ServerRequestInterface::class => [Dice::INSTANCE => function() {
                return ServerRequestFactory::fromGlobals();
            }],
        ]
    ],
    ServerRequestInterface::class => ['shared' => true],
]);
```
I'm sure you can gather that I'm wanting to inject a custom substitution for `ServerRequestInterface` but also only call my closure the first time, and use the previously instantiated object for all subsequent times.

Looking over the Dice code I don't believe what I've written above will work.

One possible solution I thought of was using a static variable inside the closure, like so:
```php
static $sr = ServerRequestFactory::fromGlobals();
return $sr;
```
But after trying that, I discovered that static variables cannot be initialized with expressions.

Any other ideas on how I could accomplish this?

**Comment by cseufert** [comment]
Use a factory class, this supports the shared flag:
```php
    'Psr\Http\Message\ServerRequestInterface' => [
      'shared' => true,
      'instanceOf' => 'Nyholm\Psr7Server\ServerRequestCreator',
      'call' => [['fromGlobals', [], Dice::CHAIN_CALL]],
    ],
```
