### ISSUE TITLE
shared dependencies not working

### ISSUE THREAD

**Issue by ghost** [Level-2/Dice#203]
When using 'shared' => true rule, Dice is creating two instances.
Here is simple example
![Снимок экрана 2022-04-26 в 14 42 10](https://user-images.githubusercontent.com/62606470/165463452-4e3324bf-0a13-462b-9b6e-fe99e00601ba.png)
Result is:
![Снимок экрана 2022-04-26 в 14 41 55](https://user-images.githubusercontent.com/62606470/165463511-04ec0f5c-c077-4749-8da0-64cf9109ffcf.png)

**Comment by TRPB** [comment]
Dice creates a single instance but stores two references to it. This is to prevent needing to always reference classes with a leading `\` so `$dice->create('Core\\Design');` will give the same instance as `$dice->create('\\Core\\Design');`

**Comment by ghost** [comment]
I think it is better to always write with a leading \ than take extra
memory and store two references to classes.

ср, 27 апр. 2022 г. в 14:50, Tom Butler ***@***.***>:
