### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Dice#72]
I'm slowly building all my components into a mini-framework based on [Aphplication](https://github.com/TomBZombie/Aphplication) and for standardisaiton/better professionalism I'm tempted to move a the projects (Aphplication, Maphper, Axel and Dice) into its own organisation ( https://github.com/Level-2 )

As Dice doesn't use the vendor name in the namespace this won't be an issue for the PHP code, however, there's a couple of problems with composer.

Before moving anything, I just wanted to check nobody here would have an issue with `TomBZombie\Dice` becoming `Level-2\Dice`

**Comment by garrettw** [comment]
I thought something like this might have been in the works. Sounds great! I'm excited to see where it goes.

**Comment by TomBZombie** [comment]
It's been 3 weeks and nobody has objected (I didn't expect anyone to) I have moved the repo. According to the question I asked over at packagist, the placeholder package with dummy composer.json should allow for the old name to still be used in people's `require` lines.

Let me know if anyone has any suggestions for `composer.json` if there are issues.

Currently the other projects are:

https://github.com/Level-2/Transphporm - A new a approach to templates in PHP
https://github.com/Level-2/Aphplication - An application server for PHP sites
https://github.com/Level-2/Maphper - An advanced ORM that supports automatic table creation

**Comment by justechn** [comment]
FYI, this change broke my composer update. After updating the package name to level-2 it started working again.

```
 Updating tombzombie/dice dev-v2.0-PHP5.4-5.5 (2c77669 => 43c8cf4)
    Checking out 43c8cf41d82008ca35a25bdb1f2f5b50fb869c0b
    43c8cf41d82008ca35a25bdb1f2f5b50fb869c0b is gone (history was rewritten?)

  [RuntimeException]
  Failed to execute git checkout '43c8cf41d82008ca35a25bdb1f2f5b50fb869c0b' -- && git reset --hard '43c8cf41d82008ca35a2
  5bdb1f2f5b50fb869c0b' --
  fatal: reference is not a tree: 43c8cf41d82008ca35a25bdb1f2f5b50fb869c0b
```

**Comment by TomBZombie** [comment]
Thanks, what did you have in your requre: line? Was it a specific branch? Perhaps I need to add all the branches to the dummy repo.

**Comment by justechn** [comment]
This is what my require line looked like

"tombzombie/dice": "dev-v2.0-PHP5.4-5.5"

**Comment by TomBZombie** [comment]
Thanks, I'll add the relevant branch to the fake repository and a `composer.json` to include the updated one
