### ISSUE TITLE
Fatal Error: Uncaught exception 'ReflectionException'

### ISSUE THREAD

**Issue by starf** [Level-2/Dice#73]
To start off, thanks for your excellent library, maybe this is more of a user-error, would be kind of you to help me out.

Fatal error: Uncaught exception 'ReflectionException' with message 'Class Db is an internal class that cannot be instantiated without invoking its constructor'

Using PHP Version 5.5.9

Using Dice 1.3.2 this works:

```
$rule = new \Dice\Rule;
$rule->shared = true;
$dice->addRule('Db', $rule);
$db = $dice->create('Db', [$dbHost, $dbUser, $dbPass, $dbName]);
```

Using Dice 2.0-legacy this doesn't work: (producing forementioned error)

```
$rule1 = ['shared' => true];
$rule2 = ['constructParams' => [$dbHost, $dbUser, $dbPass, $dbName]];
$dice->addRule('Db', $rule1);
$dice->addRule('Db', $rule2);
$db = $dice->create('Db');
```

What am i missing here?
Important to notice on 5.6.4 everything works without a hickup, leading to believe i'm simply using the wrong library but i've double checked that twice.
On that note it may be usefull to include the "legacy" version information in the code comment on top

**Comment by TomBZombie** [comment]
Thanks for pointing this out. You're right this is a regression in 2.0. I have updated the 2.0-PHP5.4-5.5 branch to account for this. 

Todo: Add a test for this

**Comment by niclaslindberg** [comment]
Hi.

Double checked the examples (for subsitution) with the code. 

According to the code the right way of declaring substitutions for interfaces (in 3.5 Default rules) should be:

    $dice->addRule(Interface::class, ['instanceOf' => YourClass::class]);

**Comment by TomBZombie** [comment]
That's correct, are you having a problem using substitutions in this way?
