### ISSUE TITLE
What PHP 5.6 features are being used?

### ISSUE THREAD

**Issue by aik099** [Level-2/Dice#74]
I wonder what of PHP 5.6 is being used, because right now I'm on PHP 5.4 want to use Dice anyway.

I've scanned `Dice.php` using the PhpStorm and it reported following issues:

* $this in Closure is allowed in PHP 5.4 only
* Argument unpacking is available in PHP 5.6 only
* List in foreach is allowed in PHP 5.5 only

Technically these later PHP version features can be achieved in different syntax on PHP 5.4 as well. I wonder if that would result in performance penalty.

**Comment by TomBZombie** [comment]
There are several features as you noticed, these all impact performance rather than features, however there is a slower performing branch here: https://github.com/TomBZombie/Dice/tree/v2.0-PHP5.4-5.5 which has the same API and features.

**Comment by aik099** [comment]
Maybe branch isn't slower because of using PHP 5.4 compatible code, bust just because PHP 5.6 is faster than PHP 5.4 when processing identical code.

**Comment by TomBZombie** [comment]
Unfortunately not. `new $class(...$params)` is considerably faster than using `$reflection->newInstanceArgs()`

**Comment by aik099** [comment]
I will keep that in mind, thanks. Unfortunately for people, that don't have PHP 5.6 where this was introduced we're stuck with `newInstanceArgs`.

**Comment by TomBZombie** [comment]
To be clear, I say "considerably faster" because it's around twice as fast in a benchmark, however this is still 0.00001 seconds compared with 0.00001, you're not going to actually notice the difference.

**Comment by TomBZombie** [comment]
It's also probably worth noting that PHP5.4 goes End Of Life in a couple of weeks: http://php.net/supported-versions.php

**Comment by aik099** [comment]
On shared hostings, that have PHP 5.4 installed no way of getting updated PHP version installed until all projects on server support that.
