### ISSUE TITLE
Dice.php not compatible with php 5.4.44

### ISSUE THREAD

**Issue by Korsani** [Level-2/Dice#76]
I run php -l Dice.php and I got :
```
PHP Parse error:  syntax error, unexpected '.', expecting ')' in Dice.php on line 66

Parse error: syntax error, unexpected '.', expecting ')' in Dice.php on line 66

Errors parsing Dice.php
```
php -v : PHP 5.4.44-0+deb7u1 (cli) (built: Aug 26 2015 12:27:40)
uname -a : Linux jhary 3.8.13-bone50 #1 SMP Tue May 13 13:24:52 UTC 2014 armv7l GNU/Linux
(yes, I'm on BeagleBone)

**Comment by aik099** [comment]
Which branch of Dice repo are you using?

**Comment by TomBZombie** [comment]
Please use the PHP 5.4-5.5 branch of Dice: https://github.com/TomBZombie/Dice/tree/v2.0-PHP5.4-5.5 

The master branch uses some PHP5.6 features for performance reasons. It's also worth noting that PHP5.4 is going end-of-life in a couple of weeks: http://php.net/supported-versions.php

**Comment by Korsani** [comment]
I took master branch. I'll try with the PHP 5.4-5.5.
For PHP version, I depend on the will of raspbian's team :)
