### ISSUE TITLE
Best practice when using 3rd party libraries

### ISSUE THREAD

**Issue by justechn** [Level-2/Dice#81]
I am using a couple of 3rd party libraries. One of them Monolog, does not use dependency injection. In order to start it I have to do something like this
```
public function __construct()
    {
        $this->logger = new Logger('defaultLogger');
        $this->logger->pushHandler(new StreamHandler('/var/log/error.log', Logger::WARNING));
    }
```

How would I convert both Logger and StreamHandler to be injected?

I'm thinking I could do this with a rule, but I can't always guarantee that the parameters will be known when Dice is created.

Thanks

**Comment by garrettw** [comment]
I assume that the potential I knows are the Logger name and the file path?

**Comment by TomBZombie** [comment]
Unfortunately you would need to change the class you have to look like this:

```php

public function __construct(Logger $logger) {
    $this->logger = $logger;
}
```

Then you can add a rule to specify the logger constructor arguments:

```php
//Firstly add a rule for the StreamHandler, we'll use a named rule because you probably don't
//want to use the same arguments for every StreamHandler

$rule = [];
$rule['instanceOf'] = 'StreamHandler';
//Assign the constructor parameters
$rule['constructParams'] = ['/var/log/error.log', Logger::WARNING];

//Add a named instance called $ErrorLog
$dice->addRule('$ErrorLog', $rule);


//Now add a rule for your original class
$rule = [];
$rule->constructParams = [ 'defaultLogger' ];
//Call pushhandler 
$rule->call = [ ['pushHandler' , ['instance' => '$ErrorLog'] ];

$dice->addRule('YourClass', $rule);
```

If you don't know the constructor parameters, there are a couple of ways. 

1. Use a closure as in place of the named instance to generate the dependency:

```php

//add a rule for your original class
$rule = [];
$rule->constructParams = [ 'defaultLogger' ];
//Call pushhandler 
$rule->call = [ ['pushHandler' , ['instance' => function() {
if ($foo) return new StreamLogger();
else return new StreamLogger('.....');
}] ];

$dice->addRule('YourClass', $rule);
```

2. Use a closure to work out the construct params:

```php

//Firstly add a rule for the StreamHandler, we'll use a named rule because you probably don't
//want to use the same arguments for every StreamHandler

$rule = [];
$rule['instanceOf'] = 'StreamHandler';
//Assign the constructor parameters

$rule['constructParams'] = [ 
	[ 'instance' => function () use ($config) { 
		return $config->errorLogFile;
	}],
	['instance' => function() use ($config) {
 		return $config->errorLogLevel;
	}]
];

```

**Comment by justechn** [comment]
Thanks, that will help.

It looks like rules will play a large part in making sure my project is setup correctly. I could possibly end up with several dozen rules. Do you recommend having a separate file where I keep all my rules, or just put them all in the same bootstrap file where I instantiated dice?

**Comment by TomBZombie** [comment]
They all need to be applied to the same `Dice` instance so it's better to keep them together. You can also supply the rules in JSON or XML format and store them in their own file.

**Comment by justechn** [comment]
So as a follow up, I want to put the 3rd party libraries in a parent class so they are available to all the child classes. However I am not having much luck getting it to work.

For example:
```
class A {
    private $p;
    public function __construct(Parser $p) {
        $this->p = $p;
    }
}

class B extends A {
    public function __construct(C $c, D $d) {
        parent::__construct();
    }
}
```

The first problem I get is an error 
```
Warning: Missing argument 1 for service\Service::__construct()
```

so I thought adding a rule might fix it. I added the following rule
```
$rule = ['constructParams' => ['Parser']];
$dice->addRule('Service', $rule);
```

However that did not seem to fix anything.

What is the best way to bring in a dependency that all child classes will use? Does it need to be injected into the child?

**Comment by garrettw** [comment]
That's not working because `A::__construct()` needs a Logger parameter, and you aren't giving it one when you do `parent::__construct();`

You need to make a Dice rule that shares the Logger instance when it's created (in addition to giving it whatever params you want). Then just put the dependency onto the classes that need it, and create your instances of them with Dice.

So yes, it needs to be injected into each child, but each child will still get the same Logger instance.

**Comment by justechn** [comment]
So it's impossible to have a parent class share its dependencies with a child? What if the parent has a function that requires a dependency? All the children have to include that dependency? That seems like it breaks separation of concern. A child should not be concerned with the parents dependencies.

**Comment by TomBZombie** [comment]
changing 

```php
class B extends A {
    public function __construct() {
        parent::__construct();
    }

    public doSomething () {
        $this->logger->addError('an error');
    }
}
```

to

```
class B extends A {
    public function __construct(Logger $logger) {
        parent::__construct($logger);
    }

    public doSomething () {
        $this->logger->addError('an error');
    }
}
```


Will have the effect you want, but as you say "All the children have to include that dependency?"

The way around this, is Favour Composition over Inheritance https://en.wikipedia.org/wiki/Composition_over_inheritance

If you rewrite your code to do this (A HAS-A Parent rather than B IS-A parent)

**Comment by justechn** [comment]
Your talking about using traits, instead of inheritance. That still requires every class to include the logger dependency. I guess there is no way around this. Thanks anyways

**Comment by TomBZombie** [comment]
Traits are still essentially inheritance, look at composition rather than inheritance and it will help you solve the problem. The primary advantage is loose rather than tight coupling.
