### ISSUE TITLE
Cannot instantiate interface

### ISSUE THREAD

**Issue by thiagodp** [Level-2/Dice#82]
Using PHP `5.5.8`, Dice `2.0`:

```php
$dice->addRule( '*', array( 'substitutions' =>
   array( 'MyInterface' => 'MyClass' ) ) );
```

Cannot instantiate interface. What's wrong?

**Comment by TomBZombie** [comment]
I was unable to replicate this exact error but did find something related:

```php


class Foo {
	public $bar;
	public function __construct(Bar $bar) {
		$this->bar = $bar;
	}
}

interface Bar {

}

class Baz implements Bar {

}

	$rule = [
			'substitutions' => ['Bar' => 'Baz']
		];
		$dice->addRule('*', $rule);

		$dice->create('Foo');


```

The string was not correctly being converted to an instance. I have updated dice to fix this, but if you're still getting the error `Cannot instantiate interface` can you post the constructor for the class you're instantiating?

**Comment by thiagodp** [comment]
Something like this:
```php
<?php
require_once 'vendor/autoload.php';

interface MyInterface {
	function one();
}

class AnotherClass {
	function bla() { echo "bla"; }
}

class MyClass implements MyInterface {
	
	private $another;
	
	function __construct( AnotherClass $another ) {
		$this->another = $another;
	}
	
	function one() { echo "one " . $this->another->bla(); }
}

$dice = new \Dice\Dice();
$dice->addRule( '*', array( 'substitutions' => array( 'MyInterface' => 'MyClass' ) ) );

$myClass = $dice->create( 'MyInterface' );
$myClass->one();
?>
```
Fatal error: Cannot instantiate interface MyInterface in ...\vendor\level-2\dice\Dice.php on line 48

**Comment by TomBZombie** [comment]
Without Dice is this is like calling:

```php
$myClass =  new  'MyInterface' ;
```

If you change 

```php
$myClass = $dice->create( 'MyInterface' );
```

to
```php
$myClass = $dice->create( 'MyClass' );
```

It will create an instance of `MyClass` and automatically inject `AnotherClass`.

**Comment by thiagodp** [comment]
Yes, i'm temporarily doing exactly this way (asking dice to create MyClass).
Do you intend to fix this problem later? Thanks.

**Comment by TomBZombie** [comment]
If you need to create an instance of 'MyClass' when you ask for an instance of 'MyInterface' you can do this:

```php
$dice->addRule('MyInterface', ['instanceOf' => 'MyClass']);
```

**Comment by thiagodp** [comment]
Worked nicely. Thank you.
