### ISSUE TITLE
PDO setAttribute is getting 5 params rather than 2 

### ISSUE THREAD

**Issue by StuTheBearded** [Level-2/Dice#85]
I'm getting the following error message when I try to create a PDO object and then call setAttribute twice.

Warning: PDO::setAttribute() expects exactly 2 parameters, 5 given

Iinitially I thought it was my mistake with the rules but after stripping them back to just the PDO rule the problem still occurs. Here is my test script
<?php 

require 'vendor/autoload.php';

$dice = new \Dice\Dice;

$dice->addRule('PDO', [
    'shared' => true,
    'constructParams' => ['pgsql:host=localhost;dbname=testdb;port=5432', 'postgres', 'somepassword'],
    'call' => [
        ['setAttribute', [PDO::ATTR_PERSISTENT, false]],
        ['setAttribute', [PDO::ATTR_ERRMODE, PDO::ERRMODE_WARNING]]
    ]
]);

$db = $dice->create('PDO');
?>

I'm running this on PHP5.6.14 the problem happens on both windows and linux machines.

**Comment by TomBZombie** [comment]
Thanks for pointing this out. PHP doesn't usually complain when you pass too many arguments to a method however I believe I've fixed the problem, can you take a look at the latest commit and let me know if it solves the issue?

**Comment by StuTheBearded** [comment]
Yes that's fixed the problem

**Comment by TomBZombie** [comment]
Thanks, I can see where this got introduced. Any remaining variables were passed for variadic function support, I've added a better implementation for handling this. Obviously this won't need porting back to the 5.4/5.5 branch as there are not variadic functions.
