### ISSUE TITLE
PHP 5.4+

### ISSUE THREAD

**Issue by thiagodp** [Level-2/Dice#87]
Hi, I think Dice `1.4.*` can require PHP `5.4` instead of requiring PHP `5.6`. I have a legacy code that uses this version but stopped working after Dice moved to Level-2, and increased PHP version.

Maybe testing with [travis-ci](https://travis-ci.org/) is an easy way to check this. Could you please check this and change `composer.json` from Dice `1.4` ?

Thanks

**Comment by garrettw** [comment]
I just checked and that wouldn't work. 1.4.* contains the splat/unpack operator (...) which didn't exist before PHP 5.6.
You'd still need to use the legacy branch.

**Comment by thiagodp** [comment]
Ok. Many thanks.

**Comment by thiagodp** [comment]
BTW, the legacy code was actually using 1.3.2. So maybe it stopped working after the migration to Level-2 because 1.3.2 (as well version 1.2.1) is not in tombzombie anymore, but also is not in Level-2.

**Comment by TomBZombie** [comment]
Yes, please use the PHP5.4-5.5 Branch available here: https://github.com/Level-2/Dice/tree/v2.0-PHP5.4-5.5 composer should install the correct version depending on your PHP version.

**Comment by thiagodp** [comment]
Tested with the mentioned version. When creating a shared instance of PDO, with a code like the following, it gives me a __Fatal Error__ on line `43` of Dice.php:
```php
Line 40: try {
Line 41:   $this->instances[$name] = $this->instances[ltrim($name, '\\')] = $class->newInstanceWithoutConstructor();	
Line 42: } catch (\ReflectionException $e) {
Line 43: $this->instances[$name] = $this->instances[ltrim($name, '\\')] = $class->newInstanceArgs($params($args, $share));
Line 44: }
```
Code that generates the error:
```php
$rules = array(
	'shared' => true,
	'constructParams' => array( $dsn, $u, $p, $options ),
	'call' => array( 'setAttribute', array( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION ) )
);
$dice->addRule( 'PDO', $rules );
```
I think the problem is in "constructParams". Is there any other way of configuring the rule?

**Comment by garrettw** [comment]
It's more likely to be in the 'call' portion. What does the fatal error say? It would be helpful to know.

**Comment by thiagodp** [comment]
Unfortunately it is just "Fatal Error", the file, and the line.

**Comment by TomBZombie** [comment]
I've managed to find a PHP5.4 box (it should be noted that PHP5.4 has been unsupported for quite some time now) and test this, it's a configuration issue. In Dice, `call` takes an array of methods to call in the syntax:

```
[
 ['method1', ['arg1', 'arg2']],
 ['method2', ['arg1', 'arg2']]
]
```

What you have at the moment is this:

```
 ['method1', ['arg1', 'arg2']]
```

To fix your problem you will need to wrap the array in an array:

```php
$rules = array(
    'shared' => true,
    'constructParams' => array( $dsn, $u, $p, $options ),
    'call' => array(
                   array( 'setAttribute', array( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION ) )
                )
);
$dice->addRule( 'PDO', $rules );
```

**Comment by thiagodp** [comment]
Thanks
