### ISSUE TITLE
Removing \ for substitutions rules ?

### ISSUE THREAD

**Issue by tontof** [Level-2/Dice#88]
I don't know if it could be an improvement, but as there is no ```ltrim(strtolower($name), '\\')``` for substitutions rules, this code does not work correctly.
```php
<?php

namespace Test {
    Interface TestInterface {}
}

namespace {
    include('autoload.php');

    class B implements \Test\TestInterface {}
    
    class A {
        public $a;

        public function __construct(\Test\TestInterface $a) {
            $this->a = $a;
        }
    }
    
    $dice = new Dice\Dice;
    // $rule = ['substitutions' => ['Test\TestInterface' => ['instance' => 'B']]]; // It works!
    $rule = ['substitutions' => ['\Test\TestInterface' => ['instance' => 'B']]];
    $dice->addRule('*', $rule);

    $a = $dice->create('A');
    
    echo get_class($a->a);
}
```
I let you see if you think it should be added or not.

**Comment by TomBZombie** [comment]
Yes, this is a known limitation, however it is mentioned in the documentation. Dice should always use class names without the leading slash. It would be possible to fix, but it adds a performance overhead that isn't really required.

**Comment by tontof** [comment]
Arf, I've effectively read this in the docs, but I forgot and did not make the connection with that :-(
