### ISSUE TITLE
substitutions and namespaces not working

### ISSUE THREAD

**Issue by hobbeshunter** [Level-2/Dice#89]
Hi,
when I try to add a substitution rule to a class using namespaces  `array_key_exists($class, $rule['substitutions'])` on line 107 fails, as a leading `\` is missing.
For me it works just changing line 106 to `$class = $param->getClass() ? '\\' . $param->getClass()->name : null;`

Cheers,
Martin

**Comment by TomBZombie** [comment]
Hi Martin,

What does you rule look like? Did you add the `\` when you added the substitution rule? If you omit the `\` when you assign the substitution it should work.

Tom

**Comment by hobbeshunter** [comment]
Hi Tom,

yeah that works. If I add a ```\``` at the first side or take one away at the second sums up to the same. But isn't this syntaktically wrong? As we want to start at the root namespace?
```
$databaseRule = ['substitutions' => ['lib\\Database\\DatabaseReal' => ['instance' => '\\lib\\Database\\' . DB ]]];
```
Wouldn't
```
$databaseRule = ['substitutions' => ['\\lib\\Database\\DatabaseReal' => ['instance' => '\\lib\\Database\\' . DB ]]];
```
be correct?

Cheers,
Martin

**Comment by tontof** [comment]
https://github.com/Level-2/Dice/issues/88#issuecomment-156832282
:-)

**Comment by TomBZombie** [comment]
This has been fixed for some time, closing.
