### ISSUE TITLE
Global rule returning already created object

### ISSUE THREAD

**Issue by obarcelonap** [Level-2/Dice#91]
I'm adding a rule for all instances requiring Monolog\Logger will use the same object:

````php
$dice->addRule('*', array(
    'substitutions' => array(
                        'Monolog\Logger' => new Logger('my-logger')
                    )
));
````

It works fine when some class needs the logger in the constructor.
But what happens if I create the object directly. By now, I think it's not supported.

The test:

````php
public function testDice() {
        $dice = new Dice();
        $myLogger = new Logger('my-logger');
        $dice->addRule('*', array(
            'substitutions' => array(
                Logger::class => $myLogger
            )
        ));
        $this->assertEquals($myLogger, $dice->create(Logger::class));
    }
````

The output:

```bash
There was 1 failure:

1) ott\test\config\LoggerConfigTest::testDice
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 Monolog\Logger Object (
-    'name' => 'my-logger'
+    'name' => null
     'handlers' => Array ()
     'processors' => Array ()
 )
`````

I don't know if this is a expected behaviour. By the way, the container should just return the instance when we are asking for it.

What do you think?

Thank you!

**Comment by obarcelonap** [comment]
Composer.json for the test

```json
{
    "require": {
        "level-2/Dice": "^2.0",
        "monolog/monolog": "~1.12"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.4"
    }
}

**Comment by TomBZombie** [comment]
This is certainly a current limitation, however is there a real use case where the is a problem?

If you run the following:

```php

class One {
    public $logger;

    public function __construct(\Monolog\Logger $logger) {
        $this->logger = $logger;
    }  
}

class Two {
    public $logger;

    public function __construct(\Monolog\Logger $logger) {
        $this->logger = $logger;
    }  
}



public function testDice() {
        $dice = new Dice();
        $myLogger = new Logger('my-logger');
        $dice->addRule('*', array(
            'substitutions' => array(
                Logger::class => $myLogger
            )
        ));

        $one = $dice->create('One');
        $two = $dice->create('Two');

        $this->assertSame($one->logger, $two->logger);
    }

```


It will work as expected. The problem is that `substitutions` is applied to function arguments and changing that ins't easy

What you really want here is the `shared` option:

```php
$logger = $dice->create('Monolog\Logger', [
    'shared' => true,
    'constructParams' => [
        'my-logger'
    ]
);

$one = $dice->create('One');

$this->assertSame($one-logger, $logger);

```

**Comment by obarcelonap** [comment]
Hi, thank you for your quick reply.

My use case: I'm implementing a library, where the project using the library can configure a logger as argument. This project is not using your container, my library is. I have the object created, I just want to bind the object to the container, using the shared option is not the solution.

I think it's more a conceptual issue. If I have configurated one rule inside the container, when I'm requesting explicitly that object I expect to receive it, not a new one.

It's not a problem for me because I'm not going to create the object with the explicit call, but it was a surprise for me that it doesn't work.

The are other containers that handles this behaviour. For example, Illuminate\Container through "instance" method:
http://laravel.com/docs/5.1/container#binding
http://laravel.com/api/5.1/Illuminate/Container/Container.html#method_instance

Best regards,

**Comment by futuretech00** [comment]
In PHP5.3 branch Dice had method assign() for this purpose, i guess.

Is there any better alternative in Master, or any danger to extend Dice with that method?

brgds,

**Comment by TomBZombie** [comment]
The simplest way is to configure dice to create the instance and set `shared` to `true` which will then provide the same instance to any constructor that needs it.

Alternatively, you can do what was done in post 1 above and use a global substitution rule to always use a specific instance.

```php
$dice->addRule('*', array(
    'substitutions' => array(
                        'Monolog\Logger' => new Logger('my-logger')
                    )
));
```

**Comment by futuretech00** [comment]
Thanks, i agree, best way is to let Dice construct all dependencies. I was just referring to obarcelonap's case, when dependency object is "already created".
I am just beginner and try wrap my head around dependency injection container, i have read somewhere, DIC cannot be used with polymorphism. Is it true, or can you provide simple example, how to use Dice? 

thanks in advace,

**Comment by TomBZombie** [comment]
I can't speak for every container, but a lot (including Dice) are designed with polymorphism in mind. The ones that don't tend to use annotations so can only ever inject a specific type. 

With dice you can use substitutions to use a different class to the one that was hinted.  For example

```php
class MyPDO extends PDO {
//...
}

class A {
    public function __constuct(PDO $pdo) { 

   }
}
```

Here, `A` needs an instance of `PDO` as a constructor argument. Instead, it's possible to get Dice to pass it an instance of `MyPDO` using the `substitutions` rule:


```php
$dice->addRule('A', [
    'substitutions' => [ 'PDO' => 'MyPDO' ]
]);
```

Doing this, you can use any subclass of `PDO` in place of a real `PDO` instance. This works with any class or interface which is type hinted.

**Comment by hartono-sulaiman-kaskus** [comment]
i also have this issue, i already have created object, let say the code
```

class One {
    public $logger;

    public function __construct(\Monolog\Logger $logger) {
        $this->logger = $logger;
    }  
}

class Two {
    public $logger;

    public function __construct(\Monolog\Logger $logger) {
        $this->logger = $logger;
    }  
}

$dice->addRule('*', array(
    'shared' => true,
    'substitutions' => array(
                        'Monolog\Logger' => $alreadyCreatedLogger
                    )
));

$logger = $dice->create('Monolog\Logger');
$logger === $alreadyCreatedLogger // will return false;

$one = $dice->create('One');
$one->logger === $alreadyCreatedLogger; // will return true;

$two = $dice->create('Two');
$two->logger === $alreadyCreatedLogger; // will return true;

```

**Comment by TomBZombie** [comment]
When you need the same instance always returned by the container you should flag the class as `shared` instead of using substitutions. Substitutions are only used for class constructors:

```php
$dice->addRule('Monolog\Logger', ['shared' => true]);
```
Which will give the same instance to class constructors and return it from the dice::create method

However as you are creating the instance outside of Dice, you already have a reference to the original logger `$alreadyCreatedLogger` in the same scope as the `$dice` instance so you shouldn't need to do this.

The answer really is to have dice managing and constructing the logger instance.
