### ISSUE TITLE
PHP version requirement?

### ISSUE THREAD

**Issue by HallofFamer** [Level-2/Dice#92]
I thought Dice was supposed to be compatible with PHP 5.4+, but looking at the source code I found that it used variadic parameters which became available after PHP 5.6? So I have a question, is it still compatible with PHP 5.4 and PHP 5.5? Or is the PHP version requirement now bumped to PHP 5.6?

**Comment by TomBZombie** [comment]
There is a separate branch for older PHP versions: https://github.com/Level-2/Dice/tree/v2.0-PHP5.4-5.5
