### ISSUE TITLE
Problem injecting with namespaces

### ISSUE THREAD

**Issue by dmelo** [Level-2/Dice#93]
I might be doing something wrong. Here is the code I'm using:
```
<?php

require_once(__DIR__ . '/../vendor/autoload.php');

use \Dice\Dice;

$dice = new Dice();

class A
{
    public $logger;
    public function __construct(\Psr\Log\LoggerInterface $logger)
    {
        $this->logger = $logger;
    }
}

$rule = [
    'substitution' => [
        ['Psr\\Log\\LoggerInterface' => ['instance' => 'Monolog\\Logger']]
    ],
];

$dice->addRule('A', $rule);
$dice->addRule('Monolog\\Logger', ['shared' => true, 'constructParams' => ['bla']]);
$a = $dice->create('A');
```

I'm getting the following error:

    Fatal error: Cannot instantiate interface Psr\Log\LoggerInterface in /home/dmelo/proj2/ghmd/vendor/level-2/dice/Dice.php on line 70

Does someone knows what I'm doing wrong?

**Comment by daniel-meister** [comment]
It might just be a typo in 'substitution' (you need an additional **s** at the end).
Unfortunately, I've no time to test the modified code at the moment...

**Comment by dmelo** [comment]
Thank you. I fixed the typo but I still have the same error. I imagine there might be something wrong with the rule. As if Dice still don't know what to do with `LoggerInterface`. But I wasn't able to figure out what.

**Comment by TomBZombie** [comment]
Hi Dmelo,

This is a syntax error. `substitutions` is a key/value array where the keys are the class name being hinted and the values are what to use instead.

Your code:

```php
$rule = [
    'substitution' => [
        ['Psr\\Log\\LoggerInterface' => ['instance' => 'Monolog\\Logger']]
    ],
];
```

Substitutions is being set to an array rather than a key/value pair. Changing it to:

```php

$rule = [
    'substitution' => [
        'Psr\\Log\\LoggerInterface' => ['instance' => 'Monolog\\Logger']
    ],
];
```

will resolve the issue :)

**Comment by TomBZombie** [comment]
I'm reopening this, as I'm going to add a RuleValidator class so peple can more easily double check the syntax of the rules added to Dice. I don't want to build this into Dice itself as it would be a performance killer.

**Comment by dmelo** [comment]
@TomBZombie, thank you very much for your help.

**Comment by TomBZombie** [comment]
I've added a validation class. Simply replace `new \Dice\Dice;` with `new \Dice\Extra\RuleValidator;` and it will throw exceptions if your rules are assigned in an invalid format. For production and improved performance, use the normal `\Dice\Dice` class, they both have the same API so enabling debugging is simply changing 1 line of code :)

**Comment by dmelo** [comment]
That is great. I will try it this night. Thank you.

**Comment by m7moud** [comment]
I have almost the same problem with another use case, here it's:
```
class A
{
    public $logger;
    public function __construct(\Psr\Log\LoggerInterface $logger)
    {
        $this->logger = $logger;
    }
}
```
and
```
class B extends A
{
}
```
and I have the global rule on `*`
```
[
    'substitutions' => [
        'Psr\\Log\\LoggerInterface' => ['instance' => 'Monolog\\Logger']
],
```
When I try to `->create('B')` I got the interface couldn't be instantiated error, yet I can `->create('A')`
