### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by garrettw** [Level-2/Dice#95]
Is Dice currently compatible with PHP 7?

**Comment by TomBZombie** [comment]
I haven't tried it yet, but there's no reason it shouldn't be, there's nothing in PHP 7 which will break it, that said I am going to make a PHP7 branch in the next few weeks that makes use of some PHP7 features.

**Comment by TomBZombie** [comment]
This was pointed out by someone via email. This causes an error in PHP7 but not in PHP 5

```php

$dice = new \Dice\Dice;

$pdo = $dice->addRule('PDO', [
    'constructParams' => ['mysql:dbname=test;host=127.0.0.1', 'u', 'p', [PDO::ATTR_EMULATE_PREPARES => false, PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]]
]);

$pdo = $dice->create('PDO');

var_dump($pdo);
var_dump($pdo->getAttribute(PDO::ATTR_ERRMODE));
var_dump($pdo->getAttribute(PDO::ATTR_EMULATE_PREPARES));

```

It gives the error:

> Fatal error: Uncaught PDOException: PDO::__construct(): SQLSTATE[HY000]: General error: attribute value must be an integer 

Oddly, the problem is line 101

```php
		else if (is_array($param)) foreach ($param as &$value) $value = $this->expand($value, $share); 	

```

Changing it to:

```php
		else if (is_array($param)) foreach ($param as $name => $value) $param[$name] = $this->expand($value, $share);

```

Fixes the problem. No idea why that would be, theoretically the two should be the same!

**Comment by Neppord** [comment]
@TomBZombie so this issue can be closed?

**Comment by libra3d** [comment]
I haven't checked the dice code at all, but using references in foreach loops could be problematic because the referenced value could be changed in a completely different place later on if not unset directly after the loop. 

```php
else if (is_array($param)) foreach ($param as &$value) $value = $this->expand($value, $share); unset($value);
```

The documentation also says that the internal array pointer is no longer used in the foreach in PHP 7, which, I suspect, may be a reason for this to not work as expected.

http://php.net/manual/en/control-structures.foreach.php
The second comment have a great example of what happens when you don't unset the referenced loop variable.

**Comment by TomBZombie** [comment]
Yeah, it looks as if that is the cause of the problem. The fix is simple at least. I'll leave this issue open for now in case anyone else discovers any further problems with PHP7. All tests pass, however so if there is a problem it will likely be obscure.

**Comment by nanodocumet** [comment]
@TomBZombie can this patch be added to v2? Latest stable release is 2.0.3 but doesn't have this patch. Thanks!

**Comment by jpirnat** [comment]
Seconding a request for a tagged release with this patch. This issue still being "open" is preventing me from using Dice for some critical configuration (PDO options that cannot be set via setAttribute after instantiation is complete, such as PDO::MYSQL_ATTR_LOCAL_INFILE).
