### ISSUE TITLE
Dice Share rule

### ISSUE THREAD

**Issue by roji430** [Level-2/Dice#97]
@TomBZombie @WyriHaximus @daniel-meister @maxwilms Dice Share instance Rule was added to a class
but after creating different object of the class ,those object are not same 
<code>
$dice= new Dice();
$rule = array('shared' => true);
$dice->addRule('\\GRcart\\Core\\Request',$rule);
var_dump($dice->getRule('\\GRcart\\Core\\Request')); 
//show array (size=1)
  'shared' => boolean true

$one=$dice->create('\\GRcart\\Core\\Request');
$two=$dice->create('\\GRcart\\Core\\Request');
var_dump($one === $two);
//shows boolean false
</code>

**Comment by TomBZombie** [comment]
I am unable to replicate this using the following test case using either the 5.6 or 5.5-5.6 branch.

```php
require_once 'grtest.php';
		$dice= new \Dice\Dice(); 
		$rule = array('shared' => true);
		$dice->addRule('\GRcart\Core\Request',$rule);
		$one=$dice->create('\GRcart\Core\Request');
		$two=$dice->create('\GRcart\Core\Request'); 

		$this->assertSame($one, $two);
```
Where grtest contains:

```php
<?php
namespace GRcart\Core;
class Request {

}
```

Which version of Dice are you using?

**Comment by roji430** [comment]
latest one download from  https://github.com/Level-2/Dice

**Comment by TomBZombie** [comment]
Which branch? 5.6? As I am unable to replicate it using the code I posted above.

**Comment by roji430** [comment]
5.6

**Comment by TomBZombie** [comment]
Using the code above I am unable to replicate the problem. Can you post the complete code you are using?

**Comment by roji430** [comment]
<code>
$dice= new GRcart\Base\Dice();
$rule = ['shared' => true];
$dice->addRule('*', $rule);


$rule = array('shared' => true);
$dice->addRule('\GRcart\Core\Request',$rule);
$one=$dice->create('\GRcart\Core\Request');
$two=$dice->create('\GRcart\Core\Request');

var_dump($one);
var_dump($two);
</code>
this will output
object(GRcart\Core\Request)[4]
  protected 'data' => 
    array (size=0)
      empty
  protected 'param' => 
    array (size=0)
      empty
  protected 'requestMethod' => string 'GET' (length=3)
  protected 'nonFilteredData' => 
    array (size=0)
      empty
object(GRcart\Core\Request)[9]
  protected 'data' => 
    array (size=0)
      empty
  protected 'param' => 
    array (size=0)
      empty
  protected 'requestMethod' => string 'GET' (length=3)
  protected 'nonFilteredData' => 
    array (size=0)
      empty
array (size=1)
  'shared' => boolean true

**Comment by TomBZombie** [comment]
Very strange, what PHP version are you on?

**Comment by roji430** [comment]
php 5.6

**Comment by roji430** [comment]
i just want to access a variable value assigned by previously created object og the class Request on Request class but second time instantiate the class the variable  is empty
like this
<code>
$dice->create('\\GRcart\\Core\\Request')->target="main";</code>
and get the value by php magic method get
i use <code>return $dice->create('\\GRcart\\Core\\Request')->target;</code>
but it is empty

**Comment by TomBZombie** [comment]
PHP5.6, Master Branch:

```php
$dice= new \Dice\Dice();
		$rule = ['shared' => true];
		$dice->addRule('*', $rule);


		$rule = array('shared' => true);
		$dice->addRule('\GRcart\Core\Request',$rule);
		$one=$dice->create('\GRcart\Core\Request');
		$two=$dice->create('\GRcart\Core\Request');

		var_dump($one === $two);
```

Evaluates to true. Please post the rest of your code. I See you've changed Dice.php (at least the namespace) did you make any other changes?

**Comment by roji430** [comment]
Yes . i change the create function to static function

**Comment by TomBZombie** [comment]
That's why then, Dice uses instance variables to store shared objects, static methods cannot access instance variables.

**Comment by roji430** [comment]
ok got  it .. can i ask you one question regarding the MVC?

**Comment by roji430** [comment]
if i make the instance variable to static.is it  solve the problem?

**Comment by TomBZombie** [comment]
You'll need to update all references to $this to self:: and possibly, however static methods are bad practice: https://r.je/static-methods-bad-practice.html

**Comment by roji430** [comment]
no the problem still remains.. i  change the static function back to normal
but problem still remain

**Comment by TomBZombie** [comment]
Please make sure you are using an unchanged version of Dice.php from this repository.

**Comment by roji430** [comment]
ok thanks a lot it solved

**Comment by roji430** [comment]
Thanks for Your Help..

**Comment by garrettw** [comment]
Just a rule of thumb... if you find yourself feeling the need to change Tom's API for one of his classes, you probably need to rethink your own code first. ;)

**Comment by roji430** [comment]
Thank you @garrettw
